### ISSUE TITLE
When initializing a new Ursula without a registry, it tries to write it to a non-existing directory.

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#1098]
```

_____   __      _________               ______
___  | / /___  ___  ____/____  ____________  /______________
__   |/ /_  / / /  /    __  / / /__  __ \_  __ \  _ \_  ___/
_  /|  / / /_/ // /___  _  /_/ /__  /_/ /  / / /  __/  /
/_/ |_/  \__,_/ \____/  _\__, / _  .___//_/ /_/\___//_/
                        /____/  /_/

version 0.1.0-alpha.23




 ,ggg,         gg
dP""Y8a        88                                   ,dPYb,
Yb, `88        88                                   IP'`Yb
 `"  88        88                                   I8  8I
     88        88                                   I8  8'
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8


the Untrusted Re-Encryption Proxy.


Is this the public-facing IPv4 address (<REDACTED>) you want to use for Ursula? [y/N]: y
Enter keyring password:
Repeat for confirmation:
Traceback (most recent call last):
  File "/home/tux/nucypher/nucypher/blockchain/eth/registry.py", line 98, in download_latest_publication
    with open(filepath, 'wb') as registry_file:  # TODO: Skip re-write if already up to date
FileNotFoundError: [Errno 2] No such file or directory: '/home/nucypher/.local/share/nucypher/contract_registry.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tux/nucypher/nucypher/cli/characters/ursula.py", line 195, in ursula
    poa=poa)
  File "/home/tux/nucypher/nucypher/config/node.py", line 289, in generate
    node_config.__write(password=password)
  File "/home/tux/nucypher/nucypher/config/node.py", line 293, in __write
    _new_installation_path = self.initialize(password=password, download_registry=self.download_registry)
  File "/home/tux/nucypher/nucypher/config/node.py", line 605, in initialize
    self.write_keyring(password=password)
  File "/home/tux/nucypher/nucypher/config/characters.py", line 94, in write_keyring
    **generation_kwargs)
  File "/home/tux/nucypher/nucypher/config/node.py", line 666, in write_keyring
    self.connect_to_blockchain()
  File "/home/tux/nucypher/nucypher/config/node.py", line 331, in connect_to_blockchain
    sync=full_sync)
  File "/home/tux/nucypher/nucypher/blockchain/eth/chains.py", line 130, in connect
    fetch_registry=fetch_registry,
  File "/home/tux/nucypher/nucypher/blockchain/eth/interfaces.py", line 154, in __init__
    self._configure_registry(fetch_registry=fetch_registry)
  File "/home/tux/nucypher/nucypher/blockchain/eth/interfaces.py", line 246, in _configure_registry
    registry = RegistryClass.from_latest_publication()
  File "/home/tux/nucypher/nucypher/blockchain/eth/registry.py", line 109, in from_latest_publication
    filepath = cls.download_latest_publication(filepath=filepath, branch=branch)
  File "/home/tux/nucypher/nucypher/blockchain/eth/registry.py", line 101, in download_latest_publication
    raise NodeConfiguration.NoConfigurationRoot
nucypher.config.node.NoConfigurationRoot
```

When you specifiy the `--config-root` flag to generate a new config in a specific root directory, it will still try to write it to the `DEFAULT_CONFIG_ROOT` path, which doesn't exist. It should only try to write to the specific root from `--config-root`.

**Comment by KPrasch** [comment]
Since a refactor of `InEthereumContractRegistry`'s usage, this issue will no longer happen since the default Ursula behavior downloads the lastest registry publication to memory on startup and does not need save it to the disk.
