### ISSUE TITLE
Grant fails with logger KeyError

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1134]

**Comment by pranav-singhal** [comment]
Ursula error stack trace:
```
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x113df2450> due to exception: [Failure instance: Traceback: <class 'KeyError'>: ''
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py:1028:emit
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/web/wsgi.py:140:write
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py:254:error
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:295:get_field
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:252:get_value
]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/web/wsgi.py", line 140, in write
    message=(data,)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py", line 254, in error
    self.emit(LogLevel.error, format, **kwargs)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_flatten.py", line 108, in flattenEvent
    field = aFormatter.get_field(fieldName, (), event)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 295, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 252, in get_value
    return kwargs[key]
builtins.KeyError: ''

```



Alice stack trace:

```
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x113b695d0> due to exception: [Failure instance: Traceback: <class 'KeyError'>: "'data'"
/Users/crypticzombie/Desktop/projects/nucypher/forkedNucypher/nucypher/nucypher/characters/control/emitters.py:226:__call__
/Users/crypticzombie/Desktop/projects/nucypher/forkedNucypher/nucypher/nucypher/characters/control/emitters.py:244:__emit_exception
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py:206:debug
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:295:get_field
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:252:get_value
]
Traceback (most recent call last):
  File "/Users/crypticzombie/Desktop/projects/nucypher/forkedNucypher/nucypher/nucypher/characters/control/emitters.py", line 226, in __call__
    return self.__emit_exception(*args, **kwargs)
  File "/Users/crypticzombie/Desktop/projects/nucypher/forkedNucypher/nucypher/nucypher/characters/control/emitters.py", line 244, in __emit_exception
    logger(message)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py", line 206, in debug
    self.emit(LogLevel.debug, format, **kwargs)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/Users/crypticzombie/Desktop/projects/nucypher/nucypher-env/lib/python3.7/site-packages/twisted/logger/_flatten.py", line 108, in flattenEvent
    field = aFormatter.get_field(fieldName, (), event)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 295, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 252, in get_value
    return kwargs[key]
builtins.KeyError: "'data'"
```

**Comment by pranav-singhal** [comment]
steps to recreate: 

1) run alice, bob and ursula using the following commands
```
nucypher ursula run --dev --federated-only
ucypher bob run --dev --federated-only --http-port 4000 --teacher-uri 127.0.0.1:10151
nucypher alice run --dev --federated-only --controller-port 3000 --teacher-uri 127.0.0.1:10151

```

2) make a `put` request to `http://localhost:3000/grant`
with the body of the request being: 

```
{
	"bob_encrypting_key": "03bc686e54ce269415d5caab2e3a38146414ed7d86e86c63e001fcc0f59c311f64",
	"label": "songs",
	"m": 1,
	"n": 1,
	"expiration": "2028-09-15T15:53:00",
	"bob_verifying_key": "03eab50a65b69f78c0cb38ecddb669b78bfdff5ada1d4a269a5afb9e7abb3cba4f"
}
```
