### ISSUE TITLE
Bob does not have make_control_transport function

### ISSUE THREAD

**Issue by arvindkalra** [nucypher/nucypher#1135]
While running `nucypher bob run --dev --federated-only --teacher-uri localhost:10151 --http-port 3002` with ursula running at port 10151. 

The following error is shown
```
Traceback (most recent call last):
  File "/home/arvindkalra/.local/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/arvindkalra/Documents/nucypher/nucypher/cli/characters/bob.py", line 151, in bob
    controller = BOB.make_control_transport()
AttributeError: 'Bob' object has no attribute 'make_control_transport'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/arvindkalra/.local/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/arvindkalra/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/arvindkalra/Documents/nucypher/nucypher/cli/characters/bob.py", line 151, in bob
    controller = BOB.make_control_transport()
AttributeError: 'Bob' object has no attribute 'make_control_transport'
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by arvindkalra** [comment]
I think the fix to this will be to replace 
``` 
controller = BOB.make_control_transport()
```
with 
```  
controller = BOB.make_web_controller(crash_on_error=click_config.debug)
```
In line: 151 of nucypher/cli/characters/bob.py

Alice and Enrico also use the same function `make_web_controller`  at line:200 and line:58 of nucypher/cli/characters/alice.py and nucypher/cli/characters/enrico.py respectively.
