### ISSUE TITLE
Prevent Tracebacks from being printed without --debug

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1151]

**Comment by derekpierre** [comment]
Example when creating new stakeholder:

```shell
derek @ Dereks-MacBook-Pro-2 ~/Documents/Github/repos/nucypher
 [5] → nucypher stake new-stakeholder --provider-uri file:///var/folders/m1/5vfcwhnj7b39kdnz_cjf3rkm0000gn/T/geth.ipc


███╗   ██╗██╗   ██╗
████╗  ██║██║   ██║
██╔██╗ ██║██║   ██║
██║╚██╗██║██║   ██║
██║ ╚████║╚██████╔╝
╚═╝  ╚═══╝ ╚═════╝


Traceback (most recent call last):
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/registry.py", line 161, in read
    with open(self.filepath, 'r') as registry_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derek/Library/Application Support/nucypher/dev_contract_registry.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/nucypher-X1j1AHHb/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/cli/config.py", line 215, in wrapper
    return func(config, *args, **kwargs)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/cli/stake.py", line 89, in stake
    blockchain=blockchain)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/actors.py", line 767, in __init__
    self.staking_agent = StakingEscrowAgent(blockchain=blockchain)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/agents.py", line 42, in __call__
    cls.__agents[cls] = super().__call__(*args, **kwargs)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/agents.py", line 91, in __init__
    use_proxy_address=self._forward_address)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/interfaces.py", line 404, in get_contract_by_name
    target_contract_records = self.registry.search(contract_name=name)
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/registry.py", line 209, in search
    registry_data = self.read()
  File "/Users/derek/Documents/Github/repos/nucypher/nucypher/blockchain/eth/registry.py", line 174, in read
    raise self.NoRegistry("No registry at filepath: {}".format(self.filepath))
nucypher.blockchain.eth.registry.NoRegistry: No registry at filepath: /Users/derek/Library/Application Support/nucypher/dev_contract_registry.json
```
