### ISSUE TITLE
Trying to run worker on sekanjabin: raises DetachedWorker exception

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1159]
```
$ nucypher ursula stake --provider-uri ipc:///tmp/geth.ipc



 ,ggg,         gg                                                     
dP""Y8a        88                                   ,dPYb,            
Yb, `88        88                                   IP'`Yb            
 `"  88        88                                   I8  8I            
     88        88                                   I8  8'            
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg 
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I 
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I 
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8


the Untrusted Re-Encryption Proxy.


Enter keyring password: 
Decrypting NuCypher keyring...
Traceback (most recent call last):
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/michwill/.local/share/virtualenvs/nucypher-kms-5SSQ9ZHE/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michwill/Projects/nucypher-kms/nucypher/cli/config.py", line 215, in wrapper
    return func(config, *args, **kwargs)
  File "/home/michwill/Projects/nucypher-kms/nucypher/cli/characters/ursula.py", line 259, in ursula
    lonely=lonely)
  File "/home/michwill/Projects/nucypher-kms/nucypher/cli/actions.py", line 265, in make_cli_character
    **config_args)
  File "/home/michwill/Projects/nucypher-kms/nucypher/config/node.py", line 164, in __call__
    return self.produce(**character_kwargs)
  File "/home/michwill/Projects/nucypher-kms/nucypher/config/characters.py", line 107, in produce
    ursula = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/michwill/Projects/nucypher-kms/nucypher/characters/lawful.py", line 907, in __init__
    stake_tracker=stake_tracker)
  File "/home/michwill/Projects/nucypher-kms/nucypher/blockchain/eth/actors.py", line 640, in __init__
    raise self.DetachedWorker
nucypher.network.nodes.DetachedWorker
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by cygnusv** [comment]
Steps from @michwill to reproduce:
```
nucypher-deploy contracts --dev --poa --provider-uri ipc:///tmp/geth.ipc

nucypher stake new-stakeholder --provider-uri ipc:///tmp/geth.ipc
nucypher stake init --provider-uri ipc:///tmp/geth.ipc

** create another account in geth for the worker

nucypher stake set-worker --provider-uri ipc:///tmp/geth.ipc

ln -s ~/.local/share/nucypher/dev_contract_registry.json ~/.local/share/nucypher/contract_registry.json

nucypher ursula init --provider-uri ipc:///tmp/geth.ipc
nucypher ursula stake --provider-uri ipc:///tmp/geth.ipc
```

**Comment by cygnusv** [comment]
@michwill I tried to reproduce but using the same address for staker and worker, and it works. I'll try again with a different worker address, but I don't expect big differences. 

Also, be aware that action `nucypher ursula stake` doesn't not exist anymore, since all stake-related operations are managed with `nucypher stake`.

**Comment by cygnusv** [comment]
@michwill Still haven't tried with a different worker address, but I can confirm that I have successfully confirmed activity with my worker, following more or less the same steps than you, but except `nucypher ursula stake`, you can run `nucypher ursula run` or `nucypher ursula confirm-activity`.

**Comment by michwill** [comment]
Yay, I started it!

**Comment by michwill** [comment]
Looks good!
Still, there is a wrong "connecting to goerli" message, but whatever!
