### ISSUE TITLE
Confirm activity doesn't work in StakeTracker loop: READ_ONLY_INTERFACE

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1214]
Running nodes are not confirming activity automatically. Traceback:

```2019-08-11T00:00:24+0000 [stake-tracker#info] Checking for new period. Current period is 18118
2019-08-11T00:00:24+0000 [stake-tracker#debug] Updated local staking cache (0 new stakes).
2019-08-11T00:00:24+0000 [stake-tracker#critical] Unhandled error during node stake tracking. [Failure instance: Traceback: <class 'nucypher.blockchain.eth.interfaces.BlockchainInterface.InterfaceError'>$
        /home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py:1272:run
        /home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py:1281:mainLoop
        /home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py:902:runUntilCurrent
        /home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/task.py:239:__call__
        --- <exception caught here> ---
        /home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/defer.py:151:maybeDeferred
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/token.py:562:__update
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py:70:wrapped
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py:672:_confirm_period
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py:70:wrapped
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py:77:wrapped
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py:662:confirm_activity
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/agents.py:279:confirm_activity
        /home/plavalaguna/nucypher/nucypher/blockchain/eth/interfaces.py:353:send_transaction
        ]
2019-08-11T00:00:24+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py", line 1272, in run
            self.mainLoop()
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py", line 1281, in mainLoop
            self.runUntilCurrent()
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/base.py", line 875, in runUntilCurrent
            f(*a, **kw)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/token.py", line 545, in _crash_gracefully
            failure.raiseException()
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
            raise self.value.with_traceback(self.tb)
          File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/token.py", line 562, in __update
            action(*args)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py", line 70, in wrapped
            return func(actor, *args, **kwargs)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py", line 672, in _confirm_period
            self.confirm_activity()  # < --- blockchain WRITE
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py", line 70, in wrapped
            return func(actor, *args, **kwargs)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py", line 77, in wrapped
            receipt = actor_method(self, *args, **kwargs)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py", line 662, in confirm_activity
            receipt = self.staking_agent.confirm_activity(worker_address=self.__worker_address)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/agents.py", line 279, in confirm_activity
            receipt = self.blockchain.send_transaction(contract_function=contract_function, sender_address=worker_address)
          File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/interfaces.py", line 353, in send_transaction
            raise self.InterfaceError(str(READ_ONLY_INTERFACE))
        nucypher.blockchain.eth.interfaces.InterfaceError: READ_ONLY_INTERFACE
```

**Comment by KPrasch** [comment]
This looks like it was a bug with account handling / TransactingPower - however we have not seen a reproduction or recurrence of this Issue.  There are successful auto-confirmations happening at this time - So I surmise it has been fixed.
