### ISSUE TITLE
Retrieving with an incorrect (but still published) label causes very strange error

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1253]
oooooooooo              oooo       
 888    888   ooooooo    888ooooo  
 888oooo88  888     888  888    888
 888    888 888     888  888    888
o888ooo888    88ooo88   o888ooo88  

the BUIDLer.

Decrypting NuCypher keyring...
Traceback (most recent call last):
  File "/home/jmyles/projects/nucypher/nucypher/characters/lawful.py", line 815, in retrieve
    capsule.attach_cfrag(pre_task.cfrag)
  File "/home/jmyles/projects/pyumbral/umbral/pre.py", line 177, in attach_cfrag
    raise UmbralCorrectnessError(error_msg, [cfrag])
umbral.pre.UmbralCorrectnessError: CFrag is not correct and cannot be attached to the Capsule

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/cli/config.py", line 220, in wrapper
    return func(config, *args, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/cli/characters/bob.py", line 213, in bob
    response = BOB.controller.retrieve(request=bob_request_data)
  File "/home/jmyles/projects/nucypher/nucypher/characters/control/interfaces.py", line 41, in wrapped
    response = func(self=instance, request=request, *args, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/characters/control/controllers.py", line 131, in retrieve
    result = super().retrieve(**self.serializer.load_retrieve_input(request=request))
  File "/home/jmyles/projects/nucypher/nucypher/characters/control/interfaces.py", line 208, in retrieve
    label=label)
  File "/home/jmyles/projects/nucypher/nucypher/characters/lawful.py", line 817, in retrieve
    task = work_order.tasks[0]  # TODO: generalize for WorkOrders with more than one capsule/task
KeyError: 0
Sentry is attempting to send 0 pending error messages

**Comment by jMyles** [comment]
Closing dupe #1252
