### ISSUE TITLE
Reading known nodes from storage is failing when `nucypher alice grant`

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1261]
```
└─ $ nucypher alice grant --teacher 206.81.17.135:9151 --bob-verifying-key 02af909a60e0265b4d21edcf05beeb7453fe24bb4ce226189fcb0bf61bcf7965a2 --bob-encrypting-key 03a78e8d93ebcd1ce39c9a8caa2decffd5539d2d2cc804c95aaf87608911e37e7a --label jarl --expiration 2019-08-30T20:07:50Z --m 3 --n 3 --debug



    / \  | (_) ___ ___
   / _ \ | | |/ __/ _ \
  / ___ \| | | (_|  __/
 /_/   \_|_|_|\___\___|

 the Authority.

Fetching latest registry from source.
Downloading contract registry from https://raw.githubusercontent.com/nucypher/ethereum-contract-registry/goerli/contract_registry.json
Enter password to unlock account 0xADA16B764e8aa666120c7Ea6E339E66730C96674: 
Enter NuCypher keyring password: 
Decrypting NuCypher keyring...
Decrypting NuCypher keyring...
Unlocking keyring.
Finished unlocking.
Fetching seednode 206.81.17.135:9151 TLS certificate
Saved TLS certificate for 0xbb01c4fE50f91eF73c5dD6eD89f38D55A6b1EdCA: /var/folders/9m/cm5wk3gj3nz_skbj_45pvbk80000gn/T/nucypher-temp-certs-ta22yxyp/0xbb01c4fE50f91eF73c5dD6eD89f38D55A6b1EdCA.pem
URSULA worker: None, staker 0xbb01c4fE50f91eF73c5dD6eD89f38D55A6b1EdCA
Using external Web3 Provider 'ipc:///Users/david/Library/Ethereum/goerli/geth.ipc'
Connecting to ipc:///Users/david/Library/Ethereum/goerli/geth.ipc
Injecting POA middleware at layer 0
Initialized new StakingEscrowAgent for 0xBc6297c0781C25A9Bc44eEe22181C98a30DC0229 with ipc:///Users/david/Library/Ethereum/goerli/geth.ipc and InMemoryContractRegistry
Initialized Stranger Ursula | (Ursula)⇀RoyalBlue Crossbones PowderBlue Ankh↽ (0xbb01c4fE50f91eF73c5dD6eD89f38D55A6b1EdCA)
Found 1 known node metadata files at /Users/david/Library/Application Support/nucypher/known_nodes/metadata
Traceback (most recent call last):
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/cli/config.py", line 219, in wrapper
    return func(config, *args, **kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/cli/characters/alice.py", line 223, in alice
    client_password=client_password)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/cli/actions.py", line 286, in make_cli_character
    **config_args)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/node.py", line 215, in __call__
    return self.produce(**character_kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/node.py", line 291, in produce
    merged_parameters = self.generate_parameters(**overrides)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/node.py", line 284, in generate_parameters
    merged_parameters = {**self.static_payload(), **self.dynamic_payload, **overrides}
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/node.py", line 385, in dynamic_payload
    self.read_known_nodes()   # Requires a connected blockchain to init Ursulas.
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/node.py", line 260, in read_known_nodes
    known_nodes = self.node_storage.all(federated_only=self.federated_only)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/storages.py", line 415, in all
    federated_only=federated_only)  # TODO: 466
  File "/Users/david/NuCypher/dev/nucypher/nucypher/config/storages.py", line 384, in __read_metadata
    node = Ursula.from_bytes(node_bytes, registry=registry, federated_only=federated_only)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/characters/lawful.py", line 1175, in from_bytes
    ursula = cls.from_public_keys(registry=registry, federated_only=federated_only, **node_info)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/characters/base.py", line 310, in from_public_keys
    return cls(is_me=False, federated_only=federated_only, crypto_power=crypto_power, *args, **kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/characters/lawful.py", line 831, in __init__
    **character_kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/characters/base.py", line 116, in __init__
    raise ValueError(f"Pass either federated only or registry.  Got '{federated_only}'. '{registry}'")
ValueError: Pass either federated only or registry.  Got 'False'. 'None'
```

**Comment by cygnusv** [comment]
Closed by #1451
