### ISSUE TITLE
`nucypher ursula init --provider ... --poa` shows no existing blockchain connection

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1268]
Perhaps, Ursula still tries to use blockchain in a non-refactored way.
```
$ nucypher ursula init --provider ipc:///home/ubuntu/.ethereum/goerli/geth.ipc --poa
...
the Untrusted Re-Encryption Proxy.


Traceback (most recent call last):
  File "/home/ubuntu/nucypher/nucypher/blockchain/eth/interfaces.py", line 710, in get_interface
    cached_interface = list(cls._interfaces.values())[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/config.py", line 219, in wrapper
    return func(config, *args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/characters/ursula.py", line 169, in ursula
    staker_address = select_client_account(emitter=emitter, prompt=prompt)
  File "/home/ubuntu/nucypher/nucypher/cli/actions.py", line 312, in select_client_account
    blockchain = BlockchainInterfaceFactory.get_interface()
  File "/home/ubuntu/nucypher/nucypher/blockchain/eth/interfaces.py", line 712, in get_interface
    raise cls.FactoryError(f"There is no existing blockchain connection.")
nucypher.blockchain.eth.interfaces.FactoryError: There is no existing blockchain connection.
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by michwill** [comment]
Basically, the reason for this is `nucypher.cli.characters.ursula` not using `BlockchainInterfaceFactory` at all

**Comment by cygnusv** [comment]
Same thing happens for Alice and Bob

**Comment by michwill** [comment]
So, as a quick fix... Do I need to pass `--checksum-address`?
