### ISSUE TITLE
Cannot load stranger-Ursula from the disk on startup.

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1279]
```
$ nucypher ursula confirm-activity



 ,ggg,         gg                                                     
dP""Y8a        88                                   ,dPYb,            
Yb, `88        88                                   IP'`Yb            
 `"  88        88                                   I8  8I            
     88        88                                   I8  8'            
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg 
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I 
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I 
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8


the Untrusted Re-Encryption Proxy.


Decrypting NuCypher keyring...
WARNING - No Bootnodes Available
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/config.py", line 219, in wrapper
    return func(config, *args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/characters/ursula.py", line 268, in ursula
    client_password=client_password)
  File "/home/ubuntu/nucypher/nucypher/cli/actions.py", line 288, in make_cli_character
    **config_args)
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 215, in __call__
    return self.produce(**character_kwargs)
  File "/home/ubuntu/nucypher/nucypher/config/characters.py", line 103, in produce
    merged_parameters = self.generate_parameters(**overrides)
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 284, in generate_parameters
    merged_parameters = {**self.static_payload(), **self.dynamic_payload, **overrides}
  File "/home/ubuntu/nucypher/nucypher/config/characters.py", line 98, in dynamic_payload
    return {**super().dynamic_payload, **payload}
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 385, in dynamic_payload
    self.read_known_nodes()   # Requires a connected blockchain to init Ursulas.
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 260, in read_known_nodes
    known_nodes = self.node_storage.all(federated_only=self.federated_only)
  File "/home/ubuntu/nucypher/nucypher/config/storages.py", line 415, in all
    federated_only=federated_only)  # TODO: 466
  File "/home/ubuntu/nucypher/nucypher/config/storages.py", line 384, in __read_metadata
    node = Ursula.from_bytes(node_bytes, registry=registry, federated_only=federated_only)
  File "/home/ubuntu/nucypher/nucypher/characters/lawful.py", line 1175, in from_bytes
    ursula = cls.from_public_keys(registry=registry, federated_only=federated_only, **node_info)
  File "/home/ubuntu/nucypher/nucypher/characters/base.py", line 310, in from_public_keys
    return cls(is_me=False, federated_only=federated_only, crypto_power=crypto_power, *args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/characters/lawful.py", line 831, in __init__
    **character_kwargs)
  File "/home/ubuntu/nucypher/nucypher/characters/base.py", line 116, in __init__
    raise ValueError(f"Pass either federated only or registry.  Got '{federated_only}'. '{registry}'")
ValueError: Pass either federated only or registry.  Got 'None'. 'None'
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by michwill** [comment]
And run
```
(nucypher) ubuntu@ip-172-31-9-209:~/nucypher$ nucypher ursula run --teacher 165.22.21.214:9151



 ,ggg,         gg                                                     
dP""Y8a        88                                   ,dPYb,            
Yb, `88        88                                   IP'`Yb            
 `"  88        88                                   I8  8I            
     88        88                                   I8  8'            
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg 
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I 
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I 
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8


the Untrusted Re-Encryption Proxy.


Decrypting NuCypher keyring...
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/config.py", line 219, in wrapper
    return func(config, *args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/characters/ursula.py", line 268, in ursula
    client_password=client_password)
  File "/home/ubuntu/nucypher/nucypher/cli/actions.py", line 288, in make_cli_character
    **config_args)
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 215, in __call__
    return self.produce(**character_kwargs)
  File "/home/ubuntu/nucypher/nucypher/config/characters.py", line 103, in produce
    merged_parameters = self.generate_parameters(**overrides)
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 284, in generate_parameters
    merged_parameters = {**self.static_payload(), **self.dynamic_payload, **overrides}
  File "/home/ubuntu/nucypher/nucypher/config/characters.py", line 98, in dynamic_payload
    return {**super().dynamic_payload, **payload}
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 385, in dynamic_payload
    self.read_known_nodes()   # Requires a connected blockchain to init Ursulas.
  File "/home/ubuntu/nucypher/nucypher/config/node.py", line 260, in read_known_nodes
    known_nodes = self.node_storage.all(federated_only=self.federated_only)
  File "/home/ubuntu/nucypher/nucypher/config/storages.py", line 415, in all
    federated_only=federated_only)  # TODO: 466
  File "/home/ubuntu/nucypher/nucypher/config/storages.py", line 384, in __read_metadata
    node = Ursula.from_bytes(node_bytes, registry=registry, federated_only=federated_only)
  File "/home/ubuntu/nucypher/nucypher/characters/lawful.py", line 1175, in from_bytes
    ursula = cls.from_public_keys(registry=registry, federated_only=federated_only, **node_info)
  File "/home/ubuntu/nucypher/nucypher/characters/base.py", line 310, in from_public_keys
    return cls(is_me=False, federated_only=federated_only, crypto_power=crypto_power, *args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/characters/lawful.py", line 831, in __init__
    **character_kwargs)
  File "/home/ubuntu/nucypher/nucypher/characters/base.py", line 116, in __init__
    raise ValueError(f"Pass either federated only or registry.  Got '{federated_only}'. '{registry}'")
ValueError: Pass either federated only or registry.  Got 'None'. 'None'
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit

```

**Comment by michwill** [comment]
And confirm-activity after `nucypher ursula forget`
```
Enter password to unlock account 0x3d510fA3a2d744Cfbc24da1c8471c62B0Ec45470: 
Enter NuCypher keyring password: 
Decrypting NuCypher keyring...
WARNING - No Bootnodes Available

Activity confirmed for period #18137 (starting at 2019-08-29 11:36:28.714395+00:00)
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/config.py", line 219, in wrapper
    return func(config, *args, **kwargs)
  File "/home/ubuntu/nucypher/nucypher/cli/characters/ursula.py", line 366, in ursula
    chain_name=URSULA.blockchain.client.chain_name)
AttributeError: 'Ursula' object has no attribute 'blockchain'
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by KPrasch** [comment]
Renamed this issue for accuracy.
