### ISSUE TITLE
Characters try to use keyring_root property, but it is now hidden

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1412]
```
>>> alice = Alice(keyring=keyring, known_nodes=[ursula], provider_uri='~/.ethereum/goerli/geth.ipc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 124, in __init__
    *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/nucypher/characters/base.py", line 131, in __init__
    keyring_root, checksum_address = keyring.keyring_root, keyring.checksum_address
AttributeError: 'NucypherKeyring' object has no attribute 'keyring_root'
```
The issue is because now `NucypherKeyring` has a property `__keyring_root` instead of `keyring_root`

**Comment by KPrasch** [comment]
Closed and tested in #1413
