### ISSUE TITLE
nucypher stake collect-reward doesn't work (wrong ABI expected?)

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1521]
```
Select staking account [0]: 3
Traceback (most recent call last):
  File "/home/michwill/tmp/nu/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/cli/characters/stake.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/cli/characters/stake.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/cli/characters/stake.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/cli/config.py", line 223, in wrapper
    return func(config, *args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/cli/characters/stake.py", line 627, in collect_reward
    reward_amount = NU.from_nunits(STAKEHOLDER.calculate_staking_reward())
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 867, in calculate_staking_reward
    staking_reward = self.staking_agent.calculate_staking_reward(staker_address=self.checksum_address)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 393, in calculate_staking_reward
    staked_amount = max(self.contract.functions.getLockedTokens(staker_address).call(),
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/web3/contract.py", line 759, in __call__
    clone._set_function_info()
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/web3/contract.py", line 769, in _set_function_info
    self.kwargs
  File "/home/michwill/tmp/nu/lib/python3.6/site-packages/web3/_utils/contracts.py", line 123, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getLockedTokens`, positional argument(s) of type `(<class 'str'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getLockedTokens`: ['getLockedTokens(address,uint16)']
Function invocation failed due to improper number of arguments.
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

Seemingly introduced with the last upgrade

**Comment by michwill** [comment]
This bug is already fixed on master. But somehow tests missed it

**Comment by michwill** [comment]
For starters, `StakingEscrowAgent.calculate_staking_reward` doesn't have a unit test

**Comment by michwill** [comment]
The only test which probably touches it is an integration test `test_stakeholder_and_ursula.py::test_collect_rewards_integration`. However, it looks like:
```python
    collection_args = ('stake', 'collect-reward',
                       '--mock-networking',
                       '--config-file', stakeholder_configuration_file_location,
                       '--no-policy-reward',
                       '--staking-reward',
                       '--staking-address', staker_address,
                       '--force')

    result = click_runner.invoke(nucypher_cli,
                                 collection_args,
                                 input=INSECURE_DEVELOPMENT_PASSWORD,
                                 catch_exceptions=False)
    assert result.exit_code == 0

    # The staker has withdrawn her staking rewards
    assert staker.token_agent.get_balance(address=staker_address) >= balance_before_collecting
```

So, it doesn't catch exceptions, and checks if `balance_after >= balance_before` (which holds true even if the balance stays unchanged due to failure)

**Comment by michwill** [comment]
As @cygnusv noted, this happened because we didn't do a release after upgrading contracts, not because some regression was introduced

**Comment by cygnusv** [comment]
Fixed by making the necessary release to pypi (see #1522)
