### ISSUE TITLE
Missing logfile - Repeated logging error on another thread

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1568]
```
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f635a6b9748> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/jmyles/.cache/nucypher/log/nucypher.log.2019925'
/home/jmyles/projects/nucypher/nucypher/blockchain/eth/decorators.py:70:wrapped
/home/jmyles/projects/nucypher/nucypher/blockchain/eth/interfaces.py:380:send_transaction
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:206:debug
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py:59:__call__
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/threadable.py:53:sync
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/logfile.py:197:write
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/logfile.py:103:write
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/threadable.py:53:sync
/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/jmyles/projects/nucypher/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/blockchain/eth/interfaces.py", line 380, in send_transaction
    self.log.debug(f"[TX-{transaction_name}] | {payload_pprint}")
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py", line 206, in debug
    self.emit(LogLevel.debug, format, **kwargs)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/jmyles/.cache/nucypher/log/nucypher.log.2019925'
```

**Comment by KPrasch** [comment]
This traceback appears to be caused by having stale log files on-disk when we made the switch to using log file rotation. 

This can be fixed by simply deleting the nucypher log cache: `rm ~/.cache/nucypher/log`.

@jMyles - Does the title "Repeated logging error on another thread" indicate something different?

Marking wontfix.
