### ISSUE TITLE
Encountering `DetachedWorker`  causes crash

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1591]
```
crawler_1   | |     |___ ___|_| |_ ___ ___ 
crawler_1   | | | | | . |   | |  _| . |  _|
crawler_1   | |_|_|_|___|_|_|_|_| |___|_|  
crawler_1   | 
crawler_1   | ========= Crawler =========
crawler_1   | 
crawler_1   | Connecting to preferred teacher nodes...
crawler_1   | Traceback (most recent call last):
crawler_1   |   File "/usr/local/bin/nucypher-monitor", line 8, in <module>
crawler_1   |     sys.exit(monitor())
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
crawler_1   |     return self.main(*args, **kwargs)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
crawler_1   |     rv = self.invoke(ctx)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
crawler_1   |     return _process_result(sub_ctx.command.invoke(sub_ctx))
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
crawler_1   |     return ctx.invoke(self.callback, **ctx.params)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
crawler_1   |     return callback(*args, **kwargs)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/cli/options.py", line 116, in wrapper
crawler_1   |     return func(**kwargs)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/monitor/cli/main.py", line 91, in crawl
crawler_1   |     influx_port=influx_port)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/monitor/crawler.py", line 161, in __init__
crawler_1   |     super().__init__(save_metadata=True, node_storage=node_storage, *args, **kwargs)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 368, in __init__
crawler_1   |     self.remember_node(node, eager=True)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 486, in remember_node
crawler_1   |     registry=self.registry)  # composed on character subclass, determines operating mode
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 1210, in verify_node
crawler_1   |     self.validate_metadata(registry=registry)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 1171, in validate_metadata
crawler_1   |     self.validate_worker(registry=registry)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 1148, in validate_worker
crawler_1   |     if not self._worker_is_bonded_to_staker(registry=registry):  # <-- Blockchain CALL
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 1103, in _worker_is_bonded_to_staker
crawler_1   |     raise self.DetachedWorker(f"Worker {self.worker_address} is detached")
crawler_1   | nucypher.network.nodes.DetachedWorker: Worker 0xe1887a501647BaD48e58fE62e6165D83EC817c79 is detached

```

**Comment by jMyles** [comment]
I think we want some variant of catch-continue here, but I'm not sure I can fully visualize the details yet.  Perhaps:

```
except ReasonWhyNodeCannotBeDiscovered:
    node.place_in_buket(ReasonWhyNodeCannotBeDiscovered)
```

In other words, each exceptional logic branch is also used as a bucket designation.

But yeah, at a high-level, I think that CaSi + monitoring causes #567 to start to look like a blocker.

**Comment by KPrasch** [comment]
I think the only reason we dont see the same behavior in master is because registry is not being passed, thus skipping this check.

**Comment by KPrasch** [comment]
Looks fixed - `verify_node` handles `DetachedWorker` and marks the node as invalid, then continues.
