### ISSUE TITLE
Checking known-nodes in interactive mode gives unhandled error

### ISSUE THREAD

**Issue by StakerSpace** [nucypher/nucypher#1599]
Having setup cassandra and working, was checking in interactive mode the amount of nodes I'm connected to, with command `Ursula(0xf56727f) >>> known_nodes`

```
Known Nodes (connected 22 / seen 20)         
Fleet State f71f8dc ⇀Plum Earth↽ ♁
54.152.254.4:9151    | (Ursula)⇀DarkMagenta Diamond Red Mountain↽ (0xcC0678E51a8237b762c09d6548d2d07285609e98)
Unhandled Error
Traceback (most recent call last):
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/internet/process.py", line 252, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/internet/process.py", line 256, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/processes.py", line 148, in lineReceived
    self.__commands[line]()
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/processes.py", line 96, in paintKnownNodes
    paint_known_nodes(emitter=self.emitter, ursula=self.ursula)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/painting.py", line 182, in paint_known_nodes
    emitter.echo(row_template.format(node.rest_url().ljust(20), node), color=color_index[node_type])
builtins.AttributeError: 'NodeSprout' object has no attribute 'rest_url'
```

Even though it gives me the information of the amount of nodes it's connected to, there is something going wrong.

**Comment by KPrasch** [comment]
Fixed, but related to https://github.com/nucypher/bytestringSplitter/pull/27
