### ISSUE TITLE
after nucypher ursula run --interactive errrors

### ISSUE THREAD

**Issue by Gribnik2K** [nucypher/nucypher#1607]
In order to avoid this error, you need to add a bit of ether to the worker's address.
``` 
Unhandled Error                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/actors.py", line 1072, in __init__                                                                 
    self.work_tracker.start(act_now=False)
 File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 512, in start                                                            [114/1197]
    d = self._tracking_task.start(interval=self._refresh_rate)                                                                                                                    
  File "/root/nucypher-env/lib/python3.7/site-packages/twisted/internet/task.py", line 194, in start                                                                              
    self()                                                                                                                                                                        
  File "/root/nucypher-env/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__                                                                           
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)                                                                                                                           
--- <exception caught here> ---                                                                                                                                                   
  File "/root/nucypher-env/lib/python3.7/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent                                                                    
    f(*a, **kw)                                                                                                                                                                   
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 525, in _crash_gracefully                                                          
    failure.raiseException()                                                                                                                                                      
  File "/root/nucypher-env/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException                                                                    
    raise self.value.with_traceback(self.tb)                                                                                                                                      
  File "/root/nucypher-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred                                                                     
    result = f(*args, **kw)                                                                                                                                                       
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 557, in _do_work                                                                   
    self.worker.confirm_activity()  # < --- blockchain WRITE                                                                                                                      
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/actors.py", line 83, in wrapped                                                                    
    return func(actor, *args, **kwargs)                                                                                                                                           
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/actors.py", line 90, in wrapped                                                                    
    receipt = actor_method(self, *args, **kwargs)                                                                                                                                 
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/actors.py", line 1100, in confirm_activity                                                         
    receipt = self.staking_agent.confirm_activity(worker_address=self.__worker_address)                                                                                           
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped                                                                
    return func(*args, **kwargs)                                                                                                                                                  
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/agents.py", line 400, in confirm_activity                                                          
    receipt = self.blockchain.send_transaction(contract_function=contract_function, sender_address=worker_address)                                                                
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped                                                                
    return func(*args, **kwargs)                                                                                                                                                  
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/interfaces.py", line 401, in send_transaction                                                      
    txhash = self.client.send_raw_transaction(signed_raw_transaction)                                                                                                             
  File "/root/nucypher-env/lib/python3.7/site-packages/nucypher/blockchain/eth/clients.py", line 235, in send_raw_transaction                                                     
    return self.w3.eth.sendRawTransaction(raw_transaction=transaction)                                                                                                            
  File "/root/nucypher-env/lib/python3.7/site-packages/web3/eth.py", line 388, in sendRawTransaction                                                                              
    [raw_transaction],                                                                                                                                                            
  File "/root/nucypher-env/lib/python3.7/site-packages/web3/manager.py", line 152, in request_blocking                                                                            
    raise ValueError(response["error"])                                                                                                                                           
builtins.ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}```

**Comment by KPrasch** [comment]
@Gribnik2K - Yes - we can provide a more useful error message here, or possible issue an early and loud warning as part of Ursula's start up requirements if it has no ether to pay for transaction gas.
