### ISSUE TITLE
weird logs on new version of nucypher - 2.0.0-beta.1

### ISSUE THREAD

**Issue by novy4** [nucypher/nucypher#1624]
nucypher stake list

 ____    __            __
/\  _`\ /\ \__        /\ \
\ \,\L\_\ \ ,_\    __ \ \ \/'\      __   _ __
 \/_\__ \\ \ \/  /'__`\\ \ , <    /'__`\/\`'__\
   /\ \L\ \ \ \_/\ \L\.\\ \ \\`\ /\  __/\ \ \/
   \ `\____\ \__\ \__/.\_\ \_\ \_\ \____\\ \_\
    \/_____/\/__/\/__/\/_/\/_/\/_/\/____/ \/_/

The Holder of Stakes.

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/config/characters.py:249:__init__
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/config/node.py:206:__init__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/config/characters.py", line 249, in __init__
    super().__init__(*args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/config/node.py", line 206, in __init__
    self.log.info(f"Fetching latest registry from source.")
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/registry.py:175:fetch_latest_publication
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/registry.py:83:fetch_latest_publication
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:206:debug
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/registry.py", line 175, in fetch_latest_publication
    registry_data_bytes = registry_source.fetch_latest_publication()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/registry.py", line 83, in fetch_latest_publication
    self.logger.debug(f"Downloading contract registry from {publication_endpoint}")
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 206, in debug
    self.emit(LogLevel.debug, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py:823:get_interface
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py:220:connect
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 823, in get_interface
    interface.connect()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 220, in connect
    self.log.info(f"Using external Web3 Provider '{self.provider_uri}'")
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py:823:get_interface
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py:224:connect
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 823, in get_interface
    interface.connect()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 224, in connect
    self.log.info("Connecting to {}".format(self.provider_uri))
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:63:get_agent
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:113:__init__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 63, in get_agent
    agent = agent_class(registry=registry, provider_uri=provider_uri)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 113, in __init__
    self.registry))
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:63:get_agent
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:113:__init__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 63, in get_agent
    agent = agent_class(registry=registry, provider_uri=provider_uri)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 113, in __init__
    self.registry))
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:63:get_agent
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:113:__init__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 63, in get_agent
    agent = agent_class(registry=registry, provider_uri=provider_uri)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 113, in __init__
    self.registry))
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:63:get_agent
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py:113:__init__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:222:info
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 63, in get_agent
    agent = agent_class(registry=registry, provider_uri=provider_uri)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 113, in __init__
    self.registry))
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f722ad1af28> due to exception: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py:600:refresh
/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py:643:__read_stakes
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:206:debug
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py:59:__call__
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:197:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:103:write
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py:53:sync
/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py:213:rotate
]
Traceback (most recent call last):
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py", line 600, in refresh
    return self.__read_stakes()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py", line 643, in __read_stakes
    self.log.debug(f"Updated {changed_records} local staking cache entries.")
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 206, in debug
    self.emit(LogLevel.debug, format, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/logger/_file.py", line 59, in __call__
    self._outFile.write(text)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 197, in write
    BaseLogFile.write(self, data)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 103, in write
    self.rotate()
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/home/novy/nucypher-venv/lib/python3.6/site-packages/twisted/python/logfile.py", line 213, in rotate
    os.remove("%s.%d" % (self.path, i))
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/novy/.cache/nucypher/log/nucypher.log.20191231'

======================================= Active Stakes =========================================

| ~ | Staker | Worker | # | Value    | Duration     | Enactment
|   | ------ | ------ | - | -------- | ------------ | -----------------------------------------
| 0 | 0x57c0 | 0x71B7 | 0 | 101936.208444278575145466 NU | 370 periods  | Jan 22 00:00 UTC - Jan 26 00:00 UTC

(nucypher-venv) novy@alex-vm-2:~$

**Comment by KPrasch** [comment]
@novy4 - Im curious if this is an artifact from a previous install - What is the *first* version you ever run on this system, and was it upgraded at some point?

**Comment by novy4** [comment]
> @novy4 - Im curious if this is an artifact from a previous install - What is the _first_ version of nucypher
> you ever ran on this system, and was it upgraded at some point?

it was updated this morning from prev version

**Comment by KPrasch** [comment]
OK.  As a temporary fix you can remove the directory `~/.cache/nucypher/log` and restart your node.

**Comment by novy4** [comment]
> OK. The Issue is with log file rotation - somehow a non-existent log file path is being generated by the twisted logger. As a temporary fix you can remove the directory `~/.cache/nucypher/log` and restart your node.

it works!
