### ISSUE TITLE
Environment variable for staker client password

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1626]
In order to preserve the ability for writing staker automation scripts, a password envvar is needed for stakers:

```
nucypher stake create --no-hw-wallet  --staking-address 0x236707E8D916e2D19eCf8c15d4441AdDDB5369fC --value 15000 --lock-periods 30 --force

 ____    __            __
/\  _`\ /\ \__        /\ \
\ \,\L\_\ \ ,_\    __ \ \ \/'\      __   _ __
 \/_\__ \\ \ \/  /'__`\\ \ , <    /'__`\/\`'__\
   /\ \L\ \ \ \_/\ \L\.\\ \ \\`\ /\  __/\ \ \/
   \ `\____\ \__\ \__/.\_\ \_\ \_\ \____\\ \_\
    \/_____/\/__/\/__/\/_/\/_/\/_/\/____/ \/_/

The Holder of Stakes.

Traceback (most recent call last):
  File "/home/kops/.local/bin/nucypher", line 11, in <module>
    sys.exit(nucypher_cli())
  File "/home/kops/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kops/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kops/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kops/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kops/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kops/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  [Previous line repeated 1 more time]
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 392, in create
    STAKEHOLDER = transacting_staker_options.create_character(emitter, config_file)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 202, in create_character
    initial_address=initial_address)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 141, in create_character
    individual_allocation=individual_allocation)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/config/node.py", line 287, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1308, in __init__
    self.assimilate(checksum_address=initial_address, password=password)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1332, in assimilate
    self.wallet.activate_account(checksum_address=checksum_address, password=password)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1272, in activate_account
    transacting_power.activate(password=password)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 160, in activate
    self.unlock_account(password=password)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 180, in unlock_account
    unlocked = self.blockchain.client.unlock_account(address=self.account, password=password, duration=duration)
  File "/home/kops/.local/lib/python3.6/site-packages/nucypher/blockchain/eth/clients.py", line 332, in unlock_account
    return self.w3.geth.personal.unlockAccount(address, password, duration)
  File "/home/kops/.local/lib/python3.6/site-packages/web3/module.py", line 43, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/kops/.local/lib/python3.6/site-packages/web3/manager.py", line 152, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'could not decrypt key with given password'}
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by likaioc** [comment]
It will be better if providing the stake account password option or providing an evvar for staker password. I'm looking forward to this feature.

**Comment by tuxxy** [comment]
I'm concerned about misuse of this envvar. How can we prevent that?

**Comment by KPrasch** [comment]
This represents too great of a security concern to be implemented.
