### ISSUE TITLE
`nucypher stake collect-reward` doesn't work with `--staking-address` flag

### ISSUE THREAD

**Issue by StakerSpace** [nucypher/nucypher#1657]
I'm trying to withdraw my rewards with the command `nucypher stake collect-reward --staking-reward --policy-reward --staking-address 0xf56727fc21bf5f1f7335c71df22e68a269283df7`

```
The Holder of Stakes.                                      

Traceback (most recent call last):
  File "/home/ilhan/nucypher-venv/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  [Previous line repeated 1 more time]
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 745, in collect_reward
    STAKEHOLDER = transacting_staker_options.create_character(emitter, config_file)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 211, in create_character
    initial_address=initial_address)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 150, in create_character
    individual_allocation=individual_allocation)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/config/node.py", line 287, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1341, in __init__
    self.assimilate(checksum_address=initial_address, password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1365, in assimilate
    self.wallet.activate_account(checksum_address=checksum_address, password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1305, in activate_account
    transacting_power.activate(password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 160, in activate
    self.unlock_account(password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 180, in unlock_account
    unlocked = self.blockchain.client.unlock_account(address=self.account, password=password, duration=duration)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/clients.py", line 332, in unlock_account
    return self.w3.geth.personal.unlockAccount(address, password, duration)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/web3/module.py", line 43, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 152, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'could not decrypt key with given password'}
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

I have also tried to collect rewards with the following flags: 

`--withdraw-address 0xf56727fc21bf5f1f7335c71df22e68a269283df7`
`--no-hw-wallet`

With both flags the same error comes up.

**Comment by michwill** [comment]
1. You, of course, run it on Staker, not Worker side?
2. Did you try one flag at a time (e.g. `--staking-reward` OR `--policy-reward`)?

**Comment by StakerSpace** [comment]
Yes sure I'm, running the Staker address, see the addresses below:
```
======================================= Active Stakes =========================================

| ~ | Staker | Worker | # | Value    | Duration     | Enactment          
|   | ------ | ------ | - | -------- | ------------ | ----------------------------------------- 
| 0 | 0xf567 | 0x27fB | 0 | 40212.922061475529892849 NU | 44 periods . | Jan 22 01:00 CET - Mar 06 01:00 CET 
| 1 | 0xf567 | 0x27fB | 1 | 142473.75651125417084403 NU | 378 periods  | Jan 22 01:00 CET - Feb 03 01:00 CET 
```

`nucypher stake collect-reward --staking-reward --staking-address 0xf56727fc21bf5f1f7335c71df22e68a269283df7`

```
The Holder of Stakes.                                      

Traceback (most recent call last):
  File "/home/ilhan/nucypher-venv/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 134, in wrapper
    return func(**kwargs)
  [Previous line repeated 1 more time]
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 745, in collect_reward
    STAKEHOLDER = transacting_staker_options.create_character(emitter, config_file)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 211, in create_character
    initial_address=initial_address)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/stake.py", line 150, in create_character
    individual_allocation=individual_allocation)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/config/node.py", line 287, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1341, in __init__
    self.assimilate(checksum_address=initial_address, password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1365, in assimilate
    self.wallet.activate_account(checksum_address=checksum_address, password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1305, in activate_account
    transacting_power.activate(password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 160, in activate
    self.unlock_account(password=password)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 180, in unlock_account
    unlocked = self.blockchain.client.unlock_account(address=self.account, password=password, duration=duration)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/clients.py", line 332, in unlock_account
    return self.w3.geth.personal.unlockAccount(address, password, duration)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/web3/module.py", line 43, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/ilhan/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 152, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'could not decrypt key with given password'}
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
```

With `--policy-reward` I get the same error

**Comment by cygnusv** [comment]
Try using the command this way `nucypher stake collect-reward --staking-reward --policy-reward`, that is, without `--staking-address 0xf56727fc21bf5f1f7335c71df22e68a269283df7`.

**Comment by StakerSpace** [comment]
The flag `--staking-address 0xf56727fc21bf5f1f7335c71df22e68a269283df7` caused the failure. With out the flag, I get prompted with which address I want to select.

**Comment by cygnusv** [comment]
The command should work also with the `--staking-address flag`. We have to work on this.
