### ISSUE TITLE
Invalid worker Stamp In Tests

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1698]
```
Unhandled error during node learning: Traceback (most recent call last):
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/k/Git/nucypher/nucypher/network/nodes.py", line 626, in keep_learning_about_nodes
    self.learn_from_teacher_node(eager=False)
  File "/home/k/Git/nucypher/nucypher/network/nodes.py", line 808, in learn_from_teacher_node
    response = self.network_middleware.get_nodes_via_rest(node=current_teacher,
  File "/home/k/Git/nucypher/nucypher/network/middleware.py", line 260, in get_nodes_via_rest
    response = self.client.get(node_or_sprout=node,
  File "/home/k/Git/nucypher/nucypher/network/middleware.py", line 117, in method_wrapper
    host, node_certificate_filepath, http_client = self.verify_and_parse_node_or_host_and_port(node_or_sprout, host, port)
  File "/home/k/Git/nucypher/nucypher/network/middleware.py", line 66, in verify_and_parse_node_or_host_and_port
    node.verify_node(network_middleware_client=self)
  File "/home/k/Git/nucypher/nucypher/network/nodes.py", line 1214, in verify_node
    self.validate_metadata(registry=registry)
  File "/home/k/Git/nucypher/nucypher/network/nodes.py", line 1175, in validate_metadata
    self.validate_worker(registry=registry)
  File "/home/k/Git/nucypher/nucypher/network/nodes.py", line 1142, in validate_worker
    raise self.StampNotSigned
nucypher.network.nodes.StampNotSigned: 

Starting Learning Loop.
Cycled teachers; New teacher is (Ursula)⇀LightCoral Alembic PapayaWhip Airplane↽ (0xDF4927e39307514e6dE950952744C8B3f7f2c454)
Learning round 21.  Teacher: (Ursula)⇀GoldenRod Saturn MediumPurple Notes↽ (0xBb5A5Cc793B4a7d5C931E1585Bd9D25a9d71d381) knew about 10 nodes, 0 were new.


```

**Comment by KPrasch** [comment]
Still seeing this in every test run's console output.

**Comment by cygnusv** [comment]
I've got this in my IBEX node:

```
2020-10-07T07:58:48+0000 [worker#debug] =========(Ursula)⇀Crimson King Ivory Alembic↽ (0x2160DCf3EAE12e21DCC1b7294859d80Ba2065589) learning at 2020-10-07 07:58:48.210476
2020-10-07T07:58:48+0000 [worker#info] Cycled teachers; New teacher is (Ursula)⇀Maroon Gemini DeepSkyBlue Atom↽ (0x4e09614836C96324689103998B4283461c203F40)
2020-10-07T07:58:48+0000 [worker#warn] Unhandled error during node learning: Traceback (most recent call last):
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/nodes.py", line 562, in _discover_or_abort
	    result = self.learn_from_teacher_node(eager=False, canceller=self._discovery_canceller)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/nodes.py", line 793, in learn_from_teacher_node
	    fleet_checksum=self.known_nodes.checksum)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/middleware.py", line 281, in get_nodes_via_rest
	    data=payload,
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/middleware.py", line 107, in method_wrapper
	    host, node_certificate_filepath, http_client = self.verify_and_parse_node_or_host_and_port(node_or_sprout, host, port)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/middleware.py", line 57, in verify_and_parse_node_or_host_and_port
	    node.verify_node(network_middleware_client=self, registry=self.registry)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/nodes.py", line 1217, in verify_node
	    self.validate_metadata(registry=registry)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/nodes.py", line 1177, in validate_metadata
	    self.validate_worker(registry=registry)
	  File "/home/plavalaguna/.local/share/virtualenvs/plavalaguna-hIHibA8V/lib/python3.6/site-packages/nucypher/network/nodes.py", line 1143, in validate_worker
	    raise self.StampNotSigned
	nucypher.network.nodes.StampNotSigned: 
```

**Comment by vepkenez** [comment]
Still happening on ibex as of 2020-11-10

**Comment by vepkenez** [comment]
This problem is encountered when a node is iterating through known nodes in preparation for /status when json is requested.
It is specific to stranger ursulas.

Probably the solution is to just return None?

**Comment by vepkenez** [comment]
It seems like in some cases it is best to ignore this issue... for example when creating a list of the 2000 known nodes of a Bob Alice or Ursula, and one of their stamps is unsigned...

When is it actually important to raise this exception?

**Comment by vepkenez** [comment]
this is being triggered on mainnet by a staker address `0xdd5d681e1044cDf5BFbba53C7456e7ea204cfC78` (https://24.21.199.33:9151/status (offline))

**Comment by KPrasch** [comment]
Cannot reproduce - Closing due to significant base divergence
