### ISSUE TITLE
Handle missing wallet address on TLS certificates

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1820]
```
Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/kieran/Git/nucypher/nucypher/network/sensors.py", line 85, in handle_measurement_errors
    failure.raiseException()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/kieran/Git/nucypher/nucypher/network/sensors.py", line 134, in maintain
    self.measure()
  File "/home/kieran/Git/nucypher/nucypher/network/sensors.py", line 183, in measure
    certificate_filepath = self._ursula.node_storage.store_node_certificate(certificate=certificate)
  File "/home/kieran/Git/nucypher/nucypher/config/storages.py", line 499, in store_node_certificate
    certificate_filepath = self._write_tls_certificate(certificate=certificate, force=force)
  File "/home/kieran/Git/nucypher/nucypher/config/storages.py", line 102, in _write_tls_certificate
    pseudonym = certificate.subject.get_attributes_for_oid(NameOID.PSEUDONYM)[0]
builtins.IndexError: list index out of range

```

**Comment by KPrasch** [comment]
This appears to be happening when an former Ursua's IP address has been re-used for a non-nucypher service - we fetch the TLS certificate and assume it has a valid checksum pseudonym.

**Comment by KPrasch** [comment]
Looks like this issue is already partially handled by the `InvalidNodeCertificate` exception - We just need to ensure that this does not result in a crash condition where possible.
