### ISSUE TITLE
Refund on fully complete worklock fails with gas exceeded allowance exception

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#1828]
All remaining work against this cassandra worklock has been completed however attempting a refund results in an exception during gas estimation.

Refunds on previous days where there was remaining work outstanding succeeded.

The nucypher installation is as per the version below but modified to add poa support to worklock.
The contract_registry.json file was provided by @KPrasch to workarround another (most likely) unrelated issue.

```
$ nucypher --version
[...]
version 2.0.0-beta.8
```

```
(nucypher) [nucypher@ml150 testnet]$ nucypher worklock status --poa --provider 'ipc:///data/ipc/goerli-geth.ipc' --network cassandra --bidder-address 0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D --registry-filepath ~/testnet/contract_registry.json

 _    _               _     _                   _
| |  | |             | |   | |                 | |
| |  | |  ___   _ __ | | __| |      ___    ___ | | __
| |/\| | / _ \ | '__|| |/ /| |     / _ \  / __|| |/ /
\  /\  /| (_) || |   |   < | |____| (_) || (__ |   <
 \/  \/  \___/ |_|   |_|\_\\_____/ \___/  \___||_|\_\


Reading Latest Chaindata...


Time
======================================================
Start Date ........ 2020-02-18 00:00:01+00:00
End Date .......... 2020-02-22 23:59:59+00:00
Duration .......... 4 days, 23:59:58
Time Remaining .... -40 days, 8:42:52

Economics
======================================================
ETH Pool .......... 2988212569216401223453
ETH Supply ........ 3533545734655703334433

Lot Size .......... 200000000 NU
Unclaimed Tokens .. 283007520687461947426322

Boosting Refund ... 200
Slowing Refund .... 100
Refund Rate ....... 28300.0
Deposit Rate ...... 56600


WorkLock Participant 0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D
=====================================================
Total Bid ............ 800010012539072276
Available Refund ..... 800010012539072276
Completed Work ....... 26378825806368293634786
Remaining Work ....... 0
Refunded Work ........ 260361423859067255705680
```

```
(nucypher) [nucypher@ml150 testnet]$ nucypher worklock refund --poa --provider 'ipc:///data/ipc/goerli-geth.ipc' --network cassandra --registry-filepath ~/testnet/contract_registry.json --bidder-address=0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D

 _    _               _     _                   _
| |  | |             | |   | |                 | |
| |  | |  ___   _ __ | | __| |      ___    ___ | | __
| |/\| | / _ \ | '__|| |/ /| |     / _ \  / __|| |/ /
\  /\  /| (_) || |   |   < | |____| (_) || (__ |   <
 \/  \/  \___/ |_|   |_|\_\\_____/ \___/  \___||_|\_\


Collect ETH refund for bidder 0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D? [y/N]: y
Submitting WorkLock refund request...
Reading Latest Chaindata...
Enter password to unlock account 0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D:
Validation error: 'code': -32000, 'message': 'gas required exceeds allowance (8000000) or always failing transaction'
Traceback (most recent call last):
  File "/home/nucypher/testnet/nucypher/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/cli/commands/worklock.py", line 257, in refund
    receipt = bidder.refund_deposit()
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1721, in refund_deposit
    receipt = self.worklock_agent.refund(checksum_address=self.checksum_address)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 1053, in refund
    receipt = self.blockchain.send_transaction(contract_function=contract_function, sender_address=checksum_address)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 528, in send_transaction
    transaction_gas_limit=transaction_gas_limit)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 410, in build_transaction
    unsigned_transaction = contract_function.buildTransaction(payload)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/web3/contract.py", line 1026, in buildTransaction
    **self.kwargs
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/web3/contract.py", line 1584, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/web3/_utils/transactions.py", line 86, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/web3/_utils/transactions.py", line 54, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimateGas(tx),
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/web3/eth.py", line 445, in estimateGas
    params,
  File "/home/nucypher/testnet/nucypher/lib/python3.6/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'gas required exceeds allowance (8000000) or always failing transaction'}
```

**Comment by KPrasch** [comment]
This is somewhat of an edge case, since it only effects individuals that participate in two separate testnet worklocks across two hard forked testnet NU tokens, with the same address, and simultaneous backward incompatible changes in the codebase.  

Marking as will not fix.
