### ISSUE TITLE
Ursula "Verifying key swapped out"

### ISSUE THREAD

**Issue by alinaloseva** [nucypher/nucypher#1829]
after running ursula via `nucypher ursula run`

here is an error message
```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in call
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/sensors.py", line 89, in handle_measurement_errors
    failure.raiseException()
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/sensors.py", line 138, in maintain
    self.measure()
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/sensors.py", line 191, in measure
    certificate_filepath=certificate_filepath)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/middleware.py", line 248, in check_rest_availability
    certificate_filepath=certificate_filepath)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/middleware.py", line 108, in method_wrapper
    host, node_certificate_filepath, http_client = self.verify_and_parse_node_or_host_and_port(node_or_sprout, host, port)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/middleware.py", line 58, in verify_and_parse_node_or_host_and_port
    node.verify_node(network_middleware_client=self, registry=self.registry)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/nodes.py", line 1251, in verify_node
    raise self.InvalidNode(message)
nucypher.network.nodes.InvalidNode: Verifying key swapped out.  It appears that someone is impersonating this node.
```

**Comment by KPrasch** [comment]
Thanks for the report! We're looking into the cause.

**Comment by svenski123** [comment]
I ran 'nucypher ursula run --interactive' yesterday and noticed the following stack trace and output a number of hours later:

```
 ,ggg,         gg
dP""Y8a        88                                   ,dPYb,
Yb, `88        88                                   IP'`Yb
 `"  88        88                                   I8  8I
     88        88                                   I8  8'
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8


the Untrusted Re-Encryption Proxy.


Decrypting NuCypher keyring...
Connecting to preferred teacher nodes...
Waiting for bonding and funding...
Worker is funded with 0.08100322403161744 ETH!
Worker is bonded to (0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D)!
Starting services...
Connecting to gemini
Broadcasting CONFIRMACTIVITY Transaction (203272.694304768 gwei @ 1536870912)...
Attached 0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D@89.44.43.179:9151
⚗ ♦ | MediumOrchid Alembic Chocolate Diamond

Type 'help' or '?' for help
Starting Ursula on 89.44.43.179:9151
Working ~ Keep Ursula Online!
Ursula(0x5BE64Fe) >>> status

⇀URSULA ⚗ ♦↽
(Ursula)⇀MediumOrchid Alembic Chocolate Diamond↽ (0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D)
Uptime .............. 0:04:02
Start Time .......... 4 minutes ago
Fleet State.......... 6f640e5 ⇀LightPink Saturn↽ ♄
Learning Status ..... Learning at 5s Intervals
Learning Round ...... Round #51
Operating Mode ...... Decentralized
Rest Interface ...... 89.44.43.179:9151
Node Storage Type ... Local
Known Nodes ......... 1112
Work Orders ......... 0
Current Teacher ..... (NodeSprout)⇀Beige King DarkSlateBlue Moon↽ (0x9980Ce7c8fcaA869030Cc122F8aA5Fc0D75C7269)
Current Period ...... 18354
Worker Address ...... 0x88b00500998682eF692E9DDE29bEa958B97AfBD9
Availability Score .. 10 (0 responders)

Ursula(0x5BE64Fe) >>> Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/sensors.py", line 89, in handle_measurement_errors
    failure.raiseException()
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/sensors.py", line 138, in maintain
    self.measure()
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/sensors.py", line 191, in measure
    certificate_filepath=certificate_filepath)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/middleware.py", line 248, in check_rest_availability
    certificate_filepath=certificate_filepath)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/middleware.py", line 108, in method_wrapper
    host, node_certificate_filepath, http_client = self.verify_and_parse_node_or_host_and_port(node_or_sprout, host, port)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/middleware.py", line 58, in verify_and_parse_node_or_host_and_port
    node.verify_node(network_middleware_client=self, registry=self.registry)
  File "/home/nucypher/gemini/lib64/python3.6/site-packages/nucypher/network/nodes.py", line 1251, in verify_node
    raise self.InvalidNode(message)
nucypher.network.nodes.InvalidNode: Verifying key swapped out.  It appears that someone is impersonating this node.

Broadcasting CONFIRMACTIVITY Transaction (264369 gwei @ 3000000000)...
```

**Comment by cygnusv** [comment]
Probably duplicated of #1843

**Comment by KPrasch** [comment]
Related to https://github.com/nucypher/nucypher/issues/1714

**Comment by KPrasch** [comment]
Hmm looking at this again - "Verifying key swapped out" is pretty vague language IMO.

**Comment by KPrasch** [comment]
This issue has not been observed or reproduced.
