### ISSUE TITLE
Availability Tracker: 2.1.0-beta.1 | [Errno 113] No route to host 

### ISSUE THREAD

**Issue by SSergey911** [nucypher/nucypher#1835]
`v2.1.0-beta.1` 
An error occurred after a few hours of working `ursula`. Also `Availability Score` changed to `Disabled`.

```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/sensors.py", line 89, in handle_measurement_errors
    failure.raiseException()
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/root/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/sensors.py", line 138, in maintain
    self.measure()
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/sensors.py", line 186, in measure
    port=responding_ursula_port)
  File "/root/nucypher-venv/lib/python3.6/site-packages/nucypher/network/middleware.py", line 173, in get_certificate
    seednode_certificate = ssl.get_server_certificate(addr=(host, port))
  File "/usr/lib/python3.6/ssl.py", line 1231, in get_server_certificate
    with  create_connection(addr) as sock:
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
builtins.OSError: [Errno 113] No route to host
```

**Comment by ppunktw** [comment]
got exactly the same issue!

**Comment by KPrasch** [comment]
Thanks for the reports!

**Comment by KPrasch** [comment]
`AvailabilityTracker` is not planned for production.  Leaving issue #2277 open and closing this issue.
