### ISSUE TITLE
Problem deserializing domains in node metadata

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1843]
**Describe the Bug**
Seems that some nodes are experiencing this error, probably related with availability computations?

**Traceback or Screenshots (Optional) **
````
Apr  6 13:45:41 do-nucypher-work nucypher[1275]: Unhandled error in Deferred:
Apr  6 13:45:41 do-nucypher-work nucypher[1275]: Traceback (most recent call last):
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     self.run()
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/usr/lib/python3.6/threading.py", line 864, in run
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     self._target(*self._args, **self._kwargs)
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     task()
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     task()
Apr  6 13:45:41 do-nucypher-work nucypher[1275]: --- <exception caught here> ---
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     result = inContext.theWork()
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     return func(*args,**kw)
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/nucypher/network/server.py", line 203, in learn_about_announced_nodes
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     node.mature()
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/nucypher/network/nodes.py", line 268, in mature
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     mature_node = self.finish()
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/bytestring_splitter/__init__.py", line 53, in finish
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     return self._receiver(**finished_values, **self._additional_kwargs)
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 1409, in from_processed_bytes
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     domains_vbytes = VariableLengthBytestring.dispense(processed_objects.pop('domains'))
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/bytestring_splitter/__init__.py", line 422, in dispense
Apr  6 13:45:41 do-nucypher-work nucypher[1275]:     raise BytestringSplittingError("This does not appear to be a VariableLengthBytestring, or is not the correct length.")
Apr  6 13:45:41 do-nucypher-work nucypher[1275]: bytestring_splitter.BytestringSplittingError: This does not appear to be a VariableLengthBytestring, or is not the correct length.
```
**System (please complete the following information):**
 - OS Version:
 - Nucypher Version:
 - Ethereum Node Version:

**Comment by mattharrop** [comment]
I have had this error.  System details:

OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-66-generic x86_64)
Nucypher: 2.1.0-beta.1
Eth node: Geth Version: 1.9.10-stable

**Comment by igorline** [comment]
Same here

OS: Ubuntu 18.04.3 LTS
Nucypher: 2.1.0-beta.1
Eth node: geth 1.9.10-stable-58cf5686

**Comment by ChuckChain** [comment]
Same:

OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)
Nucypher: 2.1.0-beta.1
Eth node: geth 1.9.12-stable-b6f1c8dc

**Comment by isaacagudo** [comment]
Same error here, I updated to 2.1.0-beta.2 and I got a core dump after some time running... Not sure if related ...

**Comment by KPrasch** [comment]
@jMyles  et. al. After some investigation it appears that the node discovery loop is being propagated with nodes from mixed network domains (Cassandra and Gemini both).  This is happening when restoring nodes from disk on Ursula startup in `nucypher.config.node.CharacterConfiguration.read_nodes_from_storages`, and possibly while engaging node discovery itself whilst handling `node_sprouts`.

Possibly related to https://github.com/nucypher/bytestringSplitter/issues/26
