### ISSUE TITLE
No indication that external signer is not running

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1848]
**Describe the Bug**

`ConnectionRefusedError`, `InvalidSignerURI` or `FileNotFoundError` is raised even when using a valid signer URI if the signer service is unreachable.  Instead of indication the signer is invalid, I expected to receive an exception indicating that clef is not running.

**To Reproduce**

Configure clef as the default signer:
`nucypher stake config --signer ~/.clef/clef.ipc`

Without clef running:
`nucypher stake create --signer ~/.clef/clef.ipc` 
or
`nucypher stake list --provider <PROVIDER URI>`

**Traceback**

```
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 227, in make_request
    with self._lock, self._socket as sock:
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 57, in __enter__
    self.sock = self._open()
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 72, in _open
    return get_ipc_socket(self.ipc_path)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 41, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory
```

```
      signer_accounts = self.__signer.accounts()
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/signers.py", line 148, in accounts
    normalized_addresses = self.w3.manager.request_blocking("account_list", [])
 ...
    sock.connect(ipc_path)
ConnectionRefusedError: [Errno 111] Connection refused

```

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 / Mac 10.15.4
 - Nucypher Version: 64d912c43ca37ca2c87b28dae8d3e444e9ff01ac
 - Ethereum Node Version:  Infura

**Comment by derekpierre** [comment]
Full stack trace

```
Traceback (most recent call last):
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/commands/stake.py", line 302, in list_stakes
    STAKEHOLDER = staker_options.create_character(emitter, config_file)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/commands/stake.py", line 167, in create_character
    *args, **kwargs
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/config/node.py", line 298, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/blockchain/eth/actors.py", line 1572, in __init__
    signer=signer)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/blockchain/eth/actors.py", line 1505, in __init__
    self.__get_accounts()
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/blockchain/eth/actors.py", line 1519, in __get_accounts
    signer_accounts = self.__signer.accounts()
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/blockchain/eth/signers.py", line 148, in accounts
    normalized_addresses = self.w3.manager.request_blocking("account_list", [])
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 227, in make_request
    with self._lock, self._socket as sock:
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 57, in __enter__
    self.sock = self._open()
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 72, in _open
    return get_ipc_socket(self.ipc_path)
  File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/providers/ipc.py", line 41, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by KPrasch** [comment]
Another full traceback 

```
(nucypher) kieran@pegasus:~/Git/nucypher$ nucypher stake list 

 ____    __            __                      
/\  _`\ /\ \__        /\ \                     
\ \,\L\_\ \ ,_\    __ \ \ \/'\      __   _ __  
 \/_\__ \\ \ \/  /'__`\\ \ , <    /'__`\/\`'__\
   /\ \L\ \ \ \_/\ \L\.\\ \ \\`\ /\  __/\ \ \/ 
   \ `\____\ \__\ \__/.\_\ \_\ \_\ \____\\ \_\ 
    \/_____/\/__/\/__/\/_/\/_/\/_/\/____/ \/_/ 
   
The Holder of Stakes.                                      

Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/commands/stake.py", line 302, in list_stakes
    STAKEHOLDER = staker_options.create_character(emitter, config_file)
  File "/home/kieran/Git/nucypher/nucypher/cli/commands/stake.py", line 167, in create_character
    *args, **kwargs
  File "/home/kieran/Git/nucypher/nucypher/config/node.py", line 298, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/actors.py", line 1572, in __init__
    signer=signer)
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/actors.py", line 1505, in __init__
    self.__get_accounts()
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/actors.py", line 1519, in __get_accounts
    signer_accounts = self.__signer.accounts()
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/signers.py", line 148, in accounts
    normalized_addresses = self.w3.manager.request_blocking("account_list", [])
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/providers/ipc.py", line 227, in make_request
    with self._lock, self._socket as sock:
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/providers/ipc.py", line 57, in __enter__
    self.sock = self._open()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/providers/ipc.py", line 72, in _open
    return get_ipc_socket(self.ipc_path)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/web3/providers/ipc.py", line 41, in get_ipc_socket
    sock.connect(ipc_path)
ConnectionRefusedError: [Errno 111] Connection refused

```
