### ISSUE TITLE
Prometheus Metrics Not Working

### ISSUE THREAD

**Issue by BisonAl** [nucypher/nucypher#1919]
**Describe the Bug**
Trying to run with `--prometheus` causes a few failures

**To Reproduce**
Run an Ursula node with the following flags:

`nucypher ursula run --network gemini --prometheus --metrics-port 9100`

**Traceback or Screenshots (Optional)**

##### 1. First Error: Pip Dependency Missing

First thing I noticed is that enabling the `--prometheus` flag will cause a crash at bootup, due to a missing prometheus import.

```
....
  File "/usr/local/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 1149, in run
    from nucypher.utilities.metrics import initialize_prometheus_exporter
  File "/usr/local/lib/python3.6/site-packages/nucypher/utilities/metrics.py", line 4, in <module>
    raise ImportError('prometheus_client is not installed - Install it and try again.')
ImportError: prometheus_client is not installed - Install it and try again.
```

Seems there's a note about this at https://github.com/nucypher/nucypher/blob/0ed41feac3ed8643d6544af58a375c7010596a70/nucypher/characters/lawful.py#L1148 though, and the workaround is just pip installing the dependency manually.

##### 2. Second Error: Metrics Port is `NoneType`

After installing prometheus via `pip install prometheus_client` however, seems a different issue comes up:

```
Decrypting ursula keyring...
Connecting to preferred teacher nodes...
Waiting for bonding and funding...
Worker is bonded to (0xFoobar)!
Worker is funded with 0.049607993 ETH!
Starting services...
✓ Database pruning
✓ Node Discovery (gemini)
✓ Availability Checks
✓ Work Tracking
Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 360, in run
    prometheus=prometheus)
  File "/usr/local/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 1150, in run
    initialize_prometheus_exporter(ursula=self, port=self._metrics_port)
  File "/usr/local/lib/python3.6/site-packages/nucypher/utilities/metrics.py", line 65, in initialize_prometheus_exporter
    reactor.listenTCP(port, factory)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)
TypeError: an integer is required (got type NoneType)
```

This error gets thrown at:
https://github.com/nucypher/nucypher/blob/0ed41feac3ed8643d6544af58a375c7010596a70/nucypher/characters/lawful.py#L1150
referencing the fact that `self._metrics_port` is still `None` set at:
https://github.com/nucypher/nucypher/blob/0ed41feac3ed8643d6544af58a375c7010596a70/nucypher/characters/lawful.py#L922.

Believe we should be setting this at:https://github.com/nucypher/nucypher/blob/1edfba2b2c4ac7c55d08c571d92c87ce1c24adae/nucypher/cli/commands/ursula.py#L338-L360 
and: https://github.com/nucypher/nucypher/blob/0ed41feac3ed8643d6544af58a375c7010596a70/nucypher/characters/lawful.py#L1101-L1111

however, doesn't seem like we do anything with that `--metrics-port` flag.

##### Potential Solution

I believe we just need to pass this flag through at:
https://github.com/nucypher/nucypher/blame/1edfba2b2c4ac7c55d08c571d92c87ce1c24adae/nucypher/cli/commands/ursula.py#L357-L360

and reference this at:
https://github.com/nucypher/nucypher/blob/0ed41feac3ed8643d6544af58a375c7010596a70/nucypher/characters/lawful.py#L1101-L1111.

**System (please complete the following information):**
 - OS Version: Linux
 - Nucypher Version: `v2.1.0-beta.2`
 - Ethereum Node Version:  `1.9.12`

**Comment by BisonAl** [comment]
@KPrasch you might have some good insight into this issue with the work that went into https://github.com/nucypher/nucypher/commit/15d7172793b4057f55270cc4466af0382e12de48, and might be the best person to point out if I'm doing something wrong or if there's a deeper issue.

**Comment by KPrasch** [comment]
@BisonAl - Were on it!

**Comment by BisonAl** [comment]
Sweet! Hopefully we can close out https://github.com/nucypher/nucypher/issues/1659 along the way as well, 2 birds one stone.

**Comment by derekpierre** [comment]
Closed via #1931, #2069.

**Comment by BisonAl** [comment]
Verified they're working for me since last Friday as well!

**Comment by KPrasch** [comment]
@BisonAl - Excellent - same here!  Thanks for opening the Issue to begin with :+1:
