### ISSUE TITLE
Errors with 2.1.0b5 & 2.0.0b11

### ISSUE THREAD

**Issue by joesixpack** [nucypher/nucypher#1963]
**Describe the Bug**
After upgrading to 2.1.0b5 but 2.0.0 was somehow installed by pipenv due to not being able to connect because gemini was unsupported, and some dependency errors I later fixed but forced ignored in the interim, manual installed 2.1.0b5.  It throws off two errors when attempting to run Ursula: not recognizing the keying password and using other commands, contract abi error.

Downgrading back to 2.0.0b11 that supports gemini then results in an account unlock with HTTP access is forbidden error.

**To Reproduce**
pipenv update nucypher

pipenv run nucypher ursula destroy

pipenv run nucypher ursula init --provider ipc:///home/j/.ethereum/goerli/geth.ipc --light --poa --worker-address <omitted> --network gemini

pipenv run nucypher ursula run --interactive --network gemini

**Traceback or Screenshots (Optional) **
j@andromeda:~$ pipenv update nucypher
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (887333)!
Installing dependencies from Pipfile.lock (887333)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 100/100 — 00:00:37
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
j@andromeda:~$ pipenv run nucypher --version
_____   __      _________               ______
___  | / /___  ___  ____/____  ____________  /______________
__   |/ /_  / / /  /    __  / / /__  __ \_  __ \  _ \_  ___/
_  /|  / / /_/ // /___  _  /_/ /__  /_/ /  / / /  __/  /
/_/ |_/  \__,_/ \____/  _\__, / _  .___//_/ /_/\___//_/
                        /____/  /_/

version 2.0.0-beta.11

j@andromeda:~$ pipenv install nucypher
Installing nucypher…
Adding nucypher to Pipfile's [packages]…
✔ Installation Succeeded
Installing dependencies from Pipfile.lock (887333)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 100/100 — 00:00:44
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
j@andromeda:~$ pipenv run nucypher --version
_____   __      _________               ______
___  | / /___  ___  ____/____  ____________  /______________
__   |/ /_  / / /  /    __  / / /__  __ \_  __ \  _ \_  ___/
_  /|  / / /_/ // /___  _  /_/ /__  /_/ /  / / /  __/  /
/_/ |_/  \__,_/ \____/  _\__, / _  .___//_/ /_/\___//_/
                        /____/  /_/

version 2.0.0-beta.11

j@andromeda:~$ pipenv uninstall nucypher
Uninstalling nucypher…
Found existing installation: nucypher 2.0.0b11
Uninstalling nucypher-2.0.0b11:
  Successfully uninstalled nucypher-2.0.0b11

Removing nucypher from Pipfile…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ca72e7)!
j@andromeda:~$ pipenv install nucypher
Installing nucypher…
Adding nucypher to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (125640) out of date, updating to (ca72e7)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (125640)!
Installing dependencies from Pipfile.lock (125640)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 98/98 — 00:00:27
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
j@andromeda:~$ pipenv run nucypher --version
_____   __      _________               ______
___  | / /___  ___  ____/____  ____________  /______________
__   |/ /_  / / /  /    __  / / /__  __ \_  __ \  _ \_  ___/
_  /|  / / /_/ // /___  _  /_/ /__  /_/ /  / / /  __/  /
/_/ |_/  \__,_/ \____/  _\__, / _  .___//_/ /_/\___//_/
                        /____/  /_/

version 2.1.0-beta.5

2.0.0b11:
Decrypting ursula keyring...
Connecting to preferred teacher nodes...
No teacher nodes available for domains: gemini
Traceback (most recent call last):
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 345, in run
    json_ipc=general_config.json_ipc
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 240, in create_character
    start_learning_now=load_seednodes)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/actions.py", line 356, in make_cli_character
    **config_args)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/config/node.py", line 233, in __call__
    return self.produce(**character_kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/config/characters.py", line 104, in produce
    ursula = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 972, in __init__
    self._crypto_power.consume_power_up(self.transacting_power)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 70, in consume_power_up
    power_up.activate(*args, **kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 160, in activate
    self.unlock_account(password=password)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 180, in unlock_account
    unlocked = self.blockchain.client.unlock_account(address=self.account, password=password, duration=duration)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/blockchain/eth/clients.py", line 335, in unlock_account
    return self.w3.geth.personal.unlockAccount(address, password, duration)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/web3/module.py", line 43, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'account unlock with HTTP access is forbidden'}

2.1.0b5:
Decrypting ursula keyring...
Connecting to preferred teacher nodes...
Failed to unlock nucypher keyring. Are you sure you provided the correct password?

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 LTS
 - Nucypher Version: 2.1.0b5 & 2.0.0.b11
 - Ethereum Node Version: 1.9.13-stable
 - Python Version: 3.6.9

**Comment by joesixpack** [comment]
ursula destroy also throws this off now:

Traceback (most recent call last):
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/config/node.py", line 322, in from_configuration_file
    node_configuration = cls(filepath=filepath, provider_process=provider_process, **assembled_params)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/config/characters.py", line 68, in __init__
    super().__init__(dev_mode=dev_mode, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'signer_uri'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
    return func(**kwargs)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 299, in destroy
    ursula_config = config_options.create_config(emitter, config_file)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 132, in create_config
    federated_only=self.federated_only)
  File "/home/j/.local/share/virtualenvs/j-DsCXoVb7/lib/python3.6/site-packages/nucypher/config/node.py", line 324, in from_configuration_file
    raise cls.ConfigurationError(e)
nucypher.config.base.ConfigurationError: __init__() got an unexpected keyword argument 'signer_uri'

Another breaking factor is 2.1.0b5 seems to init to ursula.json but 2.0.0b11 seems to init to ursula-workeraddress.json

**Comment by KPrasch** [comment]
`ValueError: {'code': -32000, 'message': 'account unlock with HTTP access is forbidden'}`

The result of a misconfigured node (infura for example) when using a nucypher version that does not support external signing.  These features were added in a recent version.

`nucypher.config.base.ConfigurationError: init() got an unexpected keyword argument 'signer_uri'`

Similar to the above Issue - The result of a configuration file generated by a newer version of nucypher, then downgraded, and running against a version of the code that does not support external signers yet. 

I can imagine two improvements here:

    - Issue a major (instead of minor) release when there are backward incompatible changes in the spirit of Semver 2.0.

    - Bump the configuration file version number every time a new field is added and provide a better error message.

@joesixpack - We are not providing formal backward-compatible guarantees until sometime after this milestone is closed: <https://github.com/nucypher/nucypher/milestone/12>.  The two items above can be understood as new Issues, but we do not have development plans to fix a version migration from 2.0.x -> 2.1.x .

Marked wontfix and closing.

**Comment by joesixpack** [comment]
@KPrasch What other configuration files are there besides what is stored in ~/.local/share/nucypher?  Because wiping all but the keys and attempting re-init will result in the same 'account unlock with HTTP access is forbidden' error when using 2.1.0b5 or 2.1.0b6.

**Comment by KPrasch** [comment]
>  What other configuration files are there besides what is stored in ~/.local/share/nucypher?

That's the only one.

> 'account unlock with HTTP access is forbidden' error when using 2.1.0b5 or 2.1.0b6.

What provider URI and signer URI are specified in your config file?

**Comment by joesixpack** [comment]
I was using the local goerli IPC.

The solution to my problem has been known at as far back as January.  Take --rpc or --http out of the geth command line.  Suggest putting it into the docs.
