### ISSUE TITLE
Nonce too low

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2002]
**Describe the Bug**
I was trying to run an Ursula for the first time and, as expected, the first thing it should do is confirm activity. It did, but immediately it tried to confirm again, reusing the same nonce.
It looks like a chain synchronization issue. 

**To Reproduce**
I'm using a brand new staker and ursula, with Infura as provider and the Keystore signer.

**Traceback or Screenshots (Optional) **
```
 ,ggg,         gg                                                     
dP""Y8a        88                                   ,dPYb,            
Yb, `88        88                                   IP'`Yb            
 `"  88        88                                   I8  8I            
     88        88                                   I8  8'            
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg 
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I 
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I 
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8

the Untrusted Re-Encryption Proxy.
Crimson King Ivory Alembic

Starting services...
Starting services...
✓ Database pruning
✓ Database pruning
Starting Learning Loop NOW.
Finished learning about all seednodes.
Found 0 known node metadata files at /home/plavalaguna/.local/share/nucypher/known_nodes/metadata
No seednodes were available after 3 attempts
Can't learn right now: Need some nodes to start learning from.
Can't learn right now: Need some nodes to start learning from.
✓ Node Discovery (ibex)
✓ Node Discovery (ibex)
✓ Availability Checks
✓ Availability Checks
Checking for new period. Current period is 18401
MISSED COMMITMENTS - 18401 missed staking commitments detected.
Made a commitment to period 18401
[TX-COMMITTONEXTPERIOD] | chainId: 4, nonce: 0, from: ..., gasPrice: 1 gwei, selector: 0x41fe00a0
Broadcasting COMMITTONEXTPERIOD Transaction (154427 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (154427 gwei @ 1000000000)...
[RECEIPT-COMMITTONEXTPERIOD] | txhash: ...
STARTED WORK TRACKING
Checking for new period. Current period is 18401
MISSED COMMITMENTS - 18401 missed staking commitments detected.
Made a commitment to period 18401
[TX-COMMITTONEXTPERIOD] | chainId: 4, nonce: 0, from: ..., gasPrice: 1 gwei, selector: 0x41fe00a0
Broadcasting COMMITTONEXTPERIOD Transaction (154427 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (154427 gwei @ 1000000000)...
Traceback (most recent call last):
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/plavalaguna/nucypher/nucypher/cli/options.py", line 147, in wrapper
    return func(**kwargs)
  File "/home/plavalaguna/nucypher/nucypher/cli/options.py", line 147, in wrapper
    return func(**kwargs)
  File "/home/plavalaguna/nucypher/nucypher/cli/options.py", line 147, in wrapper
    return func(**kwargs)
  File "/home/plavalaguna/nucypher/nucypher/cli/commands/ursula.py", line 377, in run
    prometheus=prometheus)
  File "/home/plavalaguna/nucypher/nucypher/characters/lawful.py", line 1138, in run
    self.work_tracker.start(act_now=True, requirement_func=self._availability_tracker.status)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/token.py", line 533, in start
    self._do_work()
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/token.py", line 594, in _do_work
    self.worker.commit_to_next_period()  # < --- blockchain WRITE
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/decorators.py", line 81, in wrapped
    return func(actor, *args, **kwargs)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/decorators.py", line 88, in wrapped
    receipt = actor_method(self, *args, **kwargs)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/actors.py", line 1348, in commit_to_next_period
    receipt = self.staking_agent.commit_to_next_period(worker_address=self.__worker_address)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/decorators.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/agents.py", line 483, in commit_to_next_period
    receipt = self.blockchain.send_transaction(contract_function=contract_function, sender_address=worker_address)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/decorators.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/interfaces.py", line 618, in send_transaction
    confirmations=confirmations)
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/interfaces.py", line 532, in sign_and_broadcast_transaction
    txhash = self.client.send_raw_transaction(signed_raw_transaction)  # <--- BROADCAST
  File "/home/plavalaguna/nucypher/nucypher/blockchain/eth/clients.py", line 268, in send_raw_transaction
    return self.w3.eth.sendRawTransaction(raw_transaction=transaction_bytes)
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/web3/eth.py", line 392, in sendRawTransaction
    [raw_transaction],
  File "/home/plavalaguna/.local/share/virtualenvs/nucypher-NFM6Af2v/lib/python3.6/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'nonce too low'}
```

**System (please complete the following information):**
 - OS Version: ubuntu
 - Nucypher Version: 
 - Ethereum Node Version: Infura

**Comment by KPrasch** [comment]
I think this can be addresses with stalecheck middleware in #2348
