### ISSUE TITLE
eth.waitForTransactionReceipt produces "Too many Requests" for Infura

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2067]
**Describe the Bug**
While doing a contract deployment using Infura on Rinkeby, I got this error from the `eth.waitForTransactionReceipt`. From the traceback, I think it's not related to the contract deployment but to the default polling rate induced by web3py, which is ~10 requests per second (it's actually `poll_latency: float=0.1`).

Infura gives you here some information on rate limits: 
https://infura.io/docs/ethereum/json-rpc/ratelimits

**To Reproduce**
Steps to reproduce the behavior

**Traceback or Screenshots (Optional) **
```
Traceback (most recent call last):
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/bin/nucypher-deploy", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher-deploy')()
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/cli/commands/deploy.py", line 457, in contracts
    deployment_parameters=deployment_parameters)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/actors.py", line 300, in deploy_contract
    **deployment_parameters)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/deployers.py", line 576, in deploy
    **overrides)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/deployers.py", line 531, in _deploy_essential
    **constructor_kwargs
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/interfaces.py", line 806, in deploy_contract
    confirmations=confirmations)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/interfaces.py", line 618, in send_transaction
    confirmations=confirmations)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/interfaces.py", line 541, in sign_and_broadcast_transaction
    receipt = self.client.wait_for_receipt(txhash, timeout=self.TIMEOUT)
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/clients.py", line 258, in wait_for_receipt
    receipt = self.w3.eth.waitForTransactionReceipt(transaction_hash=transaction_hash, timeout=timeout)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/eth.py", line 328, in waitForTransactionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout, poll_latency)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/_utils/transactions.py", line 101, in wait_for_transaction_receipt
    txn_receipt = web3.eth.getTransactionReceipt(txn_hash)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/eth.py", line 340, in getTransactionReceipt
    [transaction_hash],
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/cache.py", line 134, in middleware
    return make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/cache.py", line 427, in middleware
    response = make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/cache.py", line 247, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/providers/rpc.py", line 83, in make_request
    **self.get_request_kwargs()
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/web3/_utils/request.py", line 35, in make_post_request
    response.raise_for_status()
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://rinkeby.infura.io/v3/b05a9d95c9894b14a3fd96cf7c4c58b6
``` 
**System (please complete the following information):**
 - OS Version:
 - Nucypher Version:
 - Ethereum Node Version:

**Comment by cygnusv** [comment]
Fixed by #2043. Polling time for Infura was changed to 2 seconds to reduce the number of calls.
