### ISSUE TITLE
nucypher stake accounts does not work with untrusted provider

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2112]
Nucypher worklock bid, claim and status all work as expected with Infura and a local keystore signer.

However the nucypher stake accounts command does not work with the same Infura provider and local keystore signer.

The traceback produced by this command suggests it is attempting to lookup the staking address in the provider's wallet which does not have as the provider is untrusted.
As this is a read only operation, it does not need to unlock any account and should just lookup the provided staking address.
```
$ nucypher stake accounts --network ibex --provider [INFURA] --staking-address [ADDRESS]
Traceback (most recent call last):
  File "/home/nucypher/ibex/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/commands/stake.py", line 333, in accounts
    STAKEHOLDER = staker_options.create_character(emitter, config_file)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/commands/stake.py", line 196, in create_character
    return stakeholder_config.produce(initial_address=initial_address, *args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/config/node.py", line 337, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1609, in __init__
    raise Wallet.UnknownAccount(message)
nucypher.blockchain.eth.actors.UnknownAccount: 'Account [ADDRESS] is not known by this Ethereum client. Is it a HW account? If so, make sure that your device is plugged in and you use the --hw-wallet flag.'
```

#### Stake Accounts (keystore signer)
The command does not prompt for an unlock password and throws an exception.
If the command needs to unlock the account, it should prompt for the password first.
As this is a read only operation, it should not even be unlocking the account and should just lookup the provided staking address.
```
$ nucypher stake accounts --network ibex --provider [INFURA] --signer [KEYSTORE] --staking-address [ADDRESS]
Traceback (most recent call last):
  File "/home/nucypher/ibex/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/options.py", line 149, in wrapper
    return func(**kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/commands/stake.py", line 333, in accounts
    STAKEHOLDER = staker_options.create_character(emitter, config_file)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/cli/commands/stake.py", line 196, in create_character
    return stakeholder_config.produce(initial_address=initial_address, *args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/config/node.py", line 337, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1610, in __init__
    self.assimilate(checksum_address=initial_address, password=password)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1634, in assimilate
    self.wallet.activate_account(checksum_address=checksum_address, password=password)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1569, in activate_account
    transacting_power.activate(password=password)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/crypto/powers.py", line 177, in activate
    self.unlock_account(password=password)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/crypto/powers.py", line 191, in unlock_account
    duration=duration)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/nucypher/blockchain/eth/signers.py", line 411, in unlock_account
    signing_key = Account.from_key(Account.decrypt(key_metadata, password))
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/eth_account/account.py", line 150, in decrypt
    password_bytes = text_if_str(to_bytes, password)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/eth_utils/conversions.py", line 141, in text_if_str
    return to_type(text_or_primitive)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/eth_utils/decorators.py", line 70, in wrapper
    _assert_one_val(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.6/site-packages/eth_utils/decorators.py", line 35, in _assert_one_val
    "Instead, values were: %r, %r" % (args, kwargs)
TypeError: Exactly one of the passed values can be specified. Instead, values were: (None,), {}
```
**System (please complete the following information):**
 - OS Version: CentOS Linux release 7.8.2003 (Core) / Linux 3.10.0-1127.8.2.el7.x86_64
 - Nucypher Version: 2.1.0b12
 - Ethereum Node Version: Infura

**Comment by KPrasch** [comment]
Obsoleted by #2867
