### ISSUE TITLE
Ibex Ursula runs for a few days and then fails during work tracking

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2138]
I setup this ursula for the ibex testnet and it runs fine for a few days and then throws up a big traceback (example below).

This is the second time it's done it since the ibex worklock.

The ursula is configured to use infura with a local keystore signer.
```
Decrypting ursula keyring...
Connecting to preferred teacher nodes...
Waiting for bonding and funding...
Worker is bonded to (0x5BE64Fe93a646821D67D63DFF5626Ca64b72525D)!
Worker is funded with 0.099518224 ETH!
Starting services...
✓ Database pruning
✓ Node Discovery (ibex)
✓ Availability Checks
Broadcasting COMMITTONEXTPERIOD Transaction (343434 gwei @ 1000000000)...
✓ Work Tracking
Starting Ursula on 95.217.197.227:9151
Working ~ Keep Ursula Online!
status
Broadcasting COMMITTONEXTPERIOD Transaction (83113 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (209511 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (190514 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (205752 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (205803 gwei @ 1000000000)...
Broadcasting COMMITTONEXTPERIOD Transaction (200606 gwei @ 1000000000)...
Unhandled error during node work tracking. <twisted.python.failure.Failure nucypher.blockchain.eth.interfaces.InterfaceError: Transaction transmitted, but receipt returned status code 0. Full receipt:
 AttributeDict({'blockHash': HexBytes('0xc4ffa070efb42085041db05aed3a45432995154e08a61d59aecd59e55dc21b7b'), 'blockNumber': 6841067, 'contractAddress': None, 'cumulativeGasUsed': 273091, 'from': '0x82DdE37d9943228
f86DE84406090f56FbcF37811', 'gasUsed': 197428, 'logs': [], 'logsBloom': HexBytes('0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'to': '0x6A6F917a3FF3d33d2
6BB4743140F205486cD6B4B', 'transactionHash': HexBytes('0xbf41b7f8af542427e73c2db3ea7f436c51e45b23d5a37c35a3b22f6eec7a72e0'), 'transactionIndex': 2})>
Unhandled Error
Traceback (most recent call last):
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
    f(*a, **kw)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/token.py", line 563, in _crash_gracefully
    failure.raiseException()
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/token.py", line 616, in _do_work
    self.worker.commit_to_next_period()  # < --- blockchain WRITE
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 115, in wrapped
    return func(actor, *args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 123, in wrapped
    receipt = actor_method(self, *args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 1379, in commit_to_next_period
    receipt = self.staking_agent.commit_to_next_period(worker_address=self.__worker_address)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 506, in commit_to_next_period
    receipt: TxReceipt = self.blockchain.send_transaction(contract_function=contract_function, sender_address=worker_address)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 104, in wrapped
    return func(*args, **kwargs)
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 602, in send_transaction
    receipt = self.sign_and_broadcast_transaction(transaction_dict=transaction,
  File "/home/nucypher/ibex/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 566, in sign_and_broadcast_transaction
    raise self.InterfaceError(failure)
nucypher.blockchain.eth.interfaces.InterfaceError: Transaction transmitted, but receipt returned status code 0. Full receipt:
 AttributeDict({'blockHash': HexBytes('0xc4ffa070efb42085041db05aed3a45432995154e08a61d59aecd59e55dc21b7b'), 'blockNumber': 6841067, 'contractAddress': None, 'cumulativeGasUsed': 273091, 'from': '0x82DdE37d9943228f86DE84406090f56FbcF37811', 'gasUsed': 197428, 'logs': [], 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'to': '0x6A6F917a3FF3d33d26BB4743140F205486cD6B4B', 'transactionHash': HexBytes('0xbf41b7f8af542427e73c2db3ea7f436c51e45b23d5a37c35a3b22f6eec7a72e0'), 'transactionIndex': 2})
```

**Comment by KPrasch** [comment]
@svenski123 - Thanks for reporting this Issue, perhaps related to #2109, #2103.  At minimum, a retry of the failed transaction will help.

**Comment by KPrasch** [comment]
Advanced, and possibly fixed, in #2278

**Comment by KPrasch** [comment]
As of #2278 workers no longer wait for receipt as part of automated commitments, and receipt status checks are not executed, thus skipping this code block entirely.

**Comment by svenski123** [comment]
Thanks for following this up and good to know this problem won't happen in mainnet.
