### ISSUE TITLE
Strange background KeyErrors

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2156]
```
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f8cc9b2a070> due to exception: [Failure instance: Traceback: <class 'KeyError'>: "'policy_encrypting_key'"
/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/controllers.py:316:handle_request
/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/emitters.py:251:exception
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py:206:debug
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_observer.py:131:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_file.py:50:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py:252:<lambda>
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py:203:eventAsJSON
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/usr/lib/python3.8/string.py:272:get_field
/usr/lib/python3.8/string.py:229:get_value
]
Traceback (most recent call last):
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/controllers.py", line 316, in handle_request
    return self.emitter.exception(
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/emitters.py", line 251, in exception
    logger(message)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py", line 206, in debug
    self.emit(LogLevel.debug, format, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_flatten.py", line 108, in flattenEvent
    field = aFormatter.get_field(fieldName, (), event)
  File "/usr/lib/python3.8/string.py", line 272, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 229, in get_value
    return kwargs[key]
builtins.KeyError: "'policy_encrypting_key'"

PASSEDTemporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f8cc9b2a070> due to exception: [Failure instance: Traceback: <class 'KeyError'>: "'alice_verifying_key'"
```

**Comment by cygnusv** [comment]
See #724. The issue you describe here is how #724 manifests with the JSON file log observer.

**Comment by jMyles** [comment]
Seems to be a duplicate of #724.
