### ISSUE TITLE
known_nodes command freezes Ursula console

### ISSUE THREAD

**Issue by syuan100** [nucypher/nucypher#2238]
**Describe the Bug**
`known_nodes` command freezes Ursula console

**To Reproduce**
- Run Ursula in interactive mode (using `--provider`, `--signer`, and `--network` flags)
  - Full command: `nucypher ursula run --interactive --network ibex --provider wss://rinkeby.infura.io/ws/v3/XXXXXXX --signer clef:///root/.clef/clef.ipc`
- Type `known_nodes` command

**Traceback or Screenshots (Optional)**

```
Ursula(0x4FF6912) >>> known_nodes

Known Nodes (connected 1159 / seen 112)
Fleet State 06ecb3d ⇀DarkOliveGreen Mercury↽ ☿
54.218.99.172:9151   | (Ursula)⇀DarkOrchid Mountain Lime Ferry↽ (0x50e588FD89e837F28848eea537c3A5fb3c1907b3)
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/process.py", line 252, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/process.py", line 256, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/processes.py", line 138, in lineReceived
    self.__commands[line]()
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/processes.py", line 95, in paintKnownNodes
    paint_known_nodes(emitter=self.emitter, ursula=self.ursula)
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/painting/nodes.py", line 139, in paint_known_nodes
    emitter.echo(row_template.format(node.rest_url().ljust(20), node), color=color_index[node_type])
  File "/usr/local/lib/python3.7/site-packages/bytestring_splitter/__init__.py", line 76, in __getattr__
    raise AttributeError(f"{self.__class__} doesn't have a {message_name}, and it's not a partially split object either; those are {list(self.processed_objects.keys())}")
builtins.AttributeError: <class 'nucypher.network.nodes.NodeSprout'> doesn't have a rest_url, and it's not a partially split object either; those are ['domains', 'interface_signature', 'decentralized_identity_evidence', 'verifying_key', 'encrypting_key', 'certificate', 'rest_interface']
```

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 64-bit (AWS EC2)
 - Nucypher Version: version 3.0.0-beta.0
 - Ethereum Node Version:  Using Infura, with clef as signer
- Geth version: 1.9.20-stable-979fc968, Clef version: 0.0.0

**Comment by jMyles** [comment]
The underlying question is (perhaps): we do we *want* to display for the URL of a `NodeSprout`?

The choices seem to be either not displaying it at all, or parsing the URL into a `rest_interface`.

**Comment by KPrasch** [comment]
Ursula's interactive console is deprecated, so this issue can be closed.
