### ISSUE TITLE
Windows: Cannot use WSS infura providers

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2283]
Oringinally reported by @day-aaron

```
(nucypher-venv) MacBook-Air-3:~ aaronday$ nucypher stake create --hw-wallet
Traceback (most recent call last):
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 1591, in get_agent
    return cast(Agent, cls.__agents[registry.id][agent_class])
KeyError: '7430429a74211e3173f706c3adda8d9e08609aba9af2d9809500368e91190d29773c3b992b7d5f174a49001aadd2362ae8396f4cf7173fc350bf69d1d2573f2c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/clients.py", line 192, in from_w3
    client_data = w3.clientVersion.split('/')
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/main.py", line 197, in clientVersion
    return self.manager.request_blocking(RPC.web3_clientVersion, [])
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 139, in make_request
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 119, in coro_make_request
    async with self.conn as conn:
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 67, in __aenter__
    self.ws = await websockets.connect(
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronday/nucypher-venv/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  [Previous line repeated 1 more time]
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/stake.py", line 459, in create
    STAKEHOLDER = transacting_staker_options.create_character(emitter, config_file)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/stake.py", line 259, in create_character
    return opts.create_character(
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/stake.py", line 202, in create_character
    return stakeholder_config.produce(initial_address=initial_address, *args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/config/node.py", line 337, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 1769, in __init__
    super().__init__(is_me=is_me, *args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 820, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 146, in __init__
    self.token_agent = ContractAgency.get_agent(NucypherTokenAgent, registry=self.registry)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 1593, in get_agent
    agent = cast(Agent, agent_class(registry=registry, provider_uri=provider_uri))
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 105, in __init__
    self.blockchain = BlockchainInterfaceFactory.get_or_create_interface(provider_uri=provider_uri)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 1042, in get_or_create_interface
    interface = cls.get_interface(provider_uri=provider_uri)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 1030, in get_interface
    interface.connect()
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 314, in connect
    self.client = EthereumClient.from_w3(w3=self.w3)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/clients.py", line 197, in from_w3
    raise ValueError(f"Invalid client version string. Got '{w3.clientVersion}'")
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/main.py", line 197, in clientVersion
    return self.manager.request_blocking(RPC.web3_clientVersion, [])
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 139, in make_request
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 119, in coro_make_request
    async with self.conn as conn:
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 67, in __aenter__
    self.ws = await websockets.connect(
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
(nucypher-venv) MacBook-Air-3:~ aaronday$ nucypher stake create --hw-wallet
Traceback (most recent call last):
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 1591, in get_agent
    return cast(Agent, cls.__agents[registry.id][agent_class])
KeyError: '7430429a74211e3173f706c3adda8d9e08609aba9af2d9809500368e91190d29773c3b992b7d5f174a49001aadd2362ae8396f4cf7173fc350bf69d1d2573f2c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/clients.py", line 192, in from_w3
    client_data = w3.clientVersion.split('/')
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/main.py", line 197, in clientVersion
    return self.manager.request_blocking(RPC.web3_clientVersion, [])
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 139, in make_request
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 119, in coro_make_request
    async with self.conn as conn:
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 67, in __aenter__
    self.ws = await websockets.connect(
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronday/nucypher-venv/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  [Previous line repeated 1 more time]
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/stake.py", line 459, in create
    STAKEHOLDER = transacting_staker_options.create_character(emitter, config_file)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/stake.py", line 259, in create_character
    return opts.create_character(
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/stake.py", line 202, in create_character
    return stakeholder_config.produce(initial_address=initial_address, *args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/config/node.py", line 337, in produce
    character = self.CHARACTER_CLASS(**merged_parameters)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 1769, in __init__
    super().__init__(is_me=is_me, *args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 820, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 146, in __init__
    self.token_agent = ContractAgency.get_agent(NucypherTokenAgent, registry=self.registry)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 1593, in get_agent
    agent = cast(Agent, agent_class(registry=registry, provider_uri=provider_uri))
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 105, in __init__
    self.blockchain = BlockchainInterfaceFactory.get_or_create_interface(provider_uri=provider_uri)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 1042, in get_or_create_interface
    interface = cls.get_interface(provider_uri=provider_uri)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 1030, in get_interface
    interface.connect()
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 314, in connect
    self.client = EthereumClient.from_w3(w3=self.w3)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/clients.py", line 197, in from_w3
    raise ValueError(f"Invalid client version string. Got '{w3.clientVersion}'")
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/main.py", line 197, in clientVersion
    return self.manager.request_blocking(RPC.web3_clientVersion, [])
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 139, in make_request
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 119, in coro_make_request
    async with self.conn as conn:
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/web3/providers/websocket.py", line 67, in __aenter__
    self.ws = await websockets.connect(
  File "/Users/aaronday/nucypher-venv/lib/python3.8/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
(nucypher-venv) MacBook-Air-3:~ aaronday$
```

**Comment by day-aaron** [comment]
When I tried using wss, this error was shown. Switching to the HTTPS endpoint produced no error. I'm on OSX 10.15.5

**Comment by KPrasch** [comment]
Thanks for the report @day-aaron :+1:

**Comment by KPrasch** [comment]
Cannot reproduce.
