### ISSUE TITLE
Config File Checksum issues

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#2294]
**Describe the Bug**
When initing an Ursula with a --worker-address, it does not set a checksum_address in the resulting config file.
For some reason, later when running `nucypher ursula config`, it can't select the config file, even if federated_only is false, which should cause it to use the field worker_address instead of checksum_address

Steps to reproduce the behavior
`nucypher ursula init --worker-address <a proper checksum>`
`nucypher ursula config <--some options>`

**Traceback or Screenshots (Optional) **
If applicable, add the full error message / Traceback or upload screenshots to help explain your problem.
```
Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 11, in <module>
    sys.exit(nucypher_cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/options.py", line 155, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/options.py", line 155, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/commands/ursula.py", line 432, in config
    config_class=UrsulaConfiguration)
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/actions/select.py", line 260, in select_config_file
    parsed_addresses = {config_class.checksum_address_from_filepath(fp): fp for fp in config_files}
  File "/usr/local/lib/python3.7/site-packages/nucypher/cli/actions/select.py", line 260, in <dictcomp>
    parsed_addresses = {config_class.checksum_address_from_filepath(fp): fp for fp in config_files}
  File "/usr/local/lib/python3.7/site-packages/nucypher/config/node.py", line 279, in checksum_address_from_filepath
    raise RuntimeError(f"Invalid checksum address detected in configuration file at '{filepath}'.")
RuntimeError: Invalid checksum address detected in configuration file at '/root/.local/share/nucypher/ursula.json'.
```
**System (please complete the following information):**
 - OS Version: Ubuntu/docker
 - Nucypher Version: blue-oyster-mushrooms
 - Ethereum Node Version:

**Comment by KPrasch** [comment]
`checksum_address` has been deprecated form config files.
