### ISSUE TITLE
failed to run nucypher ursula run --interactive

### ISSUE THREAD

**Issue by LeapM** [nucypher/nucypher#2299]
**Describe the Bug**
when running nucypher ursula run --interactive, receives exception

**To Reproduce**
Steps to reproduce the behavior

**Traceback or Screenshots (Optional) **
(nucypher-venv) azureuser@nucypherstaker:~$ nucypher ursula run --interactive
Enter password to unlock account 0xe4D6bc8d9d6cC69515026f8C4Ef62a5a60c5d03C: 
Enter NuCypher keyring password: 
Decrypting ursula keyring...
Traceback (most recent call last):
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 1696, in get_agent
    return cast(Agent, cls.__agents[registry.id][agent_class])
KeyError: <class 'nucypher.blockchain.eth.agents.StakingEscrowAgent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 1507, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 308, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/azureuser/nucypher-venv/bin/nucypher", line 11, in <module>
    sys.exit(nucypher_cli())
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 157, in wrapper
    return func(**kwargs)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 157, in wrapper
    return func(**kwargs)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 157, in wrapper
    return func(**kwargs)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 383, in run
    json_ipc=general_config.json_ipc)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/ursula.py", line 287, in create_character
    start_learning_now=load_seednodes)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/utils.py", line 91, in make_cli_character
    **config_args)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/config/node.py", line 242, in __call__
    return self.produce(**character_kwargs)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/config/characters.py", line 109, in produce
    ursula = self.CHARACTER_CLASS(**merged_parameters)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 1080, in __init__
    block_until_ready=block_until_ready)
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 1481, in __init__
    registry=self.registry)  # type: StakingEscrowAgent
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 1698, in get_agent
    agent = cast(Agent, agent_class(registry=registry, provider_uri=provider_uri))
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 117, in __init__
    use_proxy_address=self._forward_address
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 682, in get_contract_by_name
    proxy_live_target_address = proxy_contract.functions.target().call()
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 964, in call
    **self.kwargs
  File "/home/azureuser/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 1529, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

**System (please complete the following information):**
 - OS Version: ubuntu
 - Nucypher Version: version 3.0.0-beta.1
 - Ethereum Node Version:  clef

**Comment by KPrasch** [comment]
Looks like either the wrong network - or your ethereum node is not fully synced.
