### ISSUE TITLE
StampNotSigned (In testnet)

### ISSUE THREAD

**Issue by kaushal1998** [nucypher/nucypher#2345]
**Bug Description**
When trying to run alice grant in nucypher cli, it shows this error:
`
raise self.StampNotSigned
nucypher.network.nodes.StampNotSigned
`

**To Reproduce**
Install nucypher version: 3.0.0 beta 3
Initialize ursula, alice and bob
then try command: 
`
       nucypher alice grant \
     --bob-verifying-key <BOB_VERIFYING_KEY> \
     --bob-encrypting-key <BOB_ENCRYPTING_KEY> \
     --label Test \
     --expiration 2020-10-08T10:07:50Z \
     --m 1 --n 1 --value 1 --debug
`

**Traceback**
`
Finished action 'grant', stopping (Alice)⇀SlateGray Alembic Olive Peace↽ (0x1fA7F1C9782EBf8cB36bd83fEE0026e8ac1F3cB8)
Disenchanting (Alice)⇀SlateGray Alembic Olive Peace↽ (0x1fA7F1C9782EBf8cB36bd83fEE0026e8ac1F3cB8)
Traceback (most recent call last):
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/interfaces.py", line 60, in wrapped
    return c(*args, **kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 192, in wrapper
    return func(**kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/alice.py", line 470, in grant
    return ALICE.controller.grant(request=grant_request)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/controllers.py", line 99, in wrapper
    return self.handle_request(name, request=request)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/controllers.py", line 146, in handle_request
    response = self._perform_action(action=method_name, request=request)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/controllers.py", line 152, in _perform_action
    response_data = super()._perform_action(*args, **kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/controllers.py", line 63, in _perform_action
    response = method(**params)  # < ---- INLET
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/interfaces.py", line 36, in wrapped
    return func(*args, **kwargs)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/control/interfaces.py", line 117, in grant
    new_policy = self.character.grant(bob=bob,
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/characters/lawful.py", line 312, in grant
    policy.make_arrangements(network_middleware=self.network_middleware,
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/policy/policies.py", line 510, in make_arrangements
    sampled_ursulas = self.sample(handpicked_ursulas=handpicked_ursulas,
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/policy/policies.py", line 546, in sample
    sampled_ursulas = self.sample_essential(quantity=target_sample_quantity,
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/policy/policies.py", line 757, in sample_essential
    self.alice.block_until_specific_nodes_are_known(to_check, learn_on_this_thread=discover_on_this_thread)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/nodes.py", line 658, in block_until_specific_nodes_are_known
    self.learn_from_teacher_node(eager=True)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/nodes.py", line 790, in learn_from_teacher_node
    response = self.network_middleware.get_nodes_via_rest(node=current_teacher,
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/middleware.py", line 284, in get_nodes_via_rest
    response = self.client.get(node_or_sprout=node,
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/middleware.py", line 107, in method_wrapper
    host, node_certificate_filepath, http_client = self.verify_and_parse_node_or_host_and_port(node_or_sprout, host, port)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/middleware.py", line 57, in verify_and_parse_node_or_host_and_port
    node.verify_node(network_middleware_client=self, registry=self.registry)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/nodes.py", line 1217, in verify_node
    self.validate_metadata(registry=registry)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/nodes.py", line 1177, in validate_metadata
    self.validate_worker(registry=registry)
  File "/home/local/ASUAD/kmhalgi/Nucypher/nucypher-venv/lib/python3.8/site-packages/nucypher/network/nodes.py", line 1143, in validate_worker
    raise self.StampNotSigned
nucypher.network.nodes.StampNotSigned
`

**System:**
 - OS Version: Ubuntu 20.04
 - Nucypher Version: 3.0.0 beta 3

**Comment by jMyles** [comment]
@kaushal12#8118: Is it possible that you init'd Ursula as `--federated-only`, but then `Alice` without it?

**Comment by KPrasch** [comment]
```
**Cycled teachers; New teacher is (NodeSprout)⇀PaleGoldenRod Cancer RosyBrown Airplane↽ (0xA1640D1f8Ac735A9363497C62e93054bd4266272)**
Initialized Stranger Ursula | (Ursula)⇀PaleGoldenRod Cancer RosyBrown Airplane↽ (0xA1640D1f8Ac735A9363497C62e93054bd4266272)
Saved TLS certificate for PaleGoldenRod Cancer RosyBrown Airplane 0xA1640D1f8Ac735A9363497C62e93054bd4266272: /home/local/ASUAD/kmhalgi/.local/share/nucypher/known_nodes/certificates/0xA1640D1f8Ac735A9363497C62e93054bd4266272.pem
No registry provided for decentralized stranger node verification - on-chain Staking verification will not be performed.
**Cycled teachers; New teacher is (NodeSprout)⇀Beige Aries DarkSlateBlue Rook↽ (0xB273777A784e0E4855FC0717bC3AF6d43023f04a)**
Finished action 'grant', stopping (Alice)⇀SlateGray Alembic Olive Peace↽ (0x1fA7F1C9782EBf8cB36bd83fEE0026e8ac1F3cB8)
Disenchanting (Alice)⇀SlateGray Alembic Olive Peace↽ (0x1fA7F1C9782EBf8cB36bd83fEE0026e8ac1F3cB8)
Traceback (most recent call last):
```

**Comment by jMyles** [comment]
The node that was causing the problem, `PaleGoldenRod Cancer RosyBrown Airplane 0xA1640D1f8Ac735A9363497C62e93054bd4266272` (https://34.224.41.141:9151/status), does not appear to be up, and does not appear to have been successfully visited by other nodes.

I surmise that what we're looking at here is a new problem introduced in Blue Oyster Mushrooms which is failing to catch some variant of a timeout exception, and is thus failing at the validation stage, having never received metadata including the node's identity evidence.

Secondarily, even if this node were intentionally spreading metadata without identity evidence, we need a better failure mode.

**Comment by cygnusv** [comment]
@jMyles there's an open issue from before blue oyster where ursulas report the same traceback during learning.

Invalid worker Stamp In Tests · Issue #1698

**Comment by KPrasch** [comment]
Related to #2150

**Comment by vepkenez** [comment]
and #1698

**Comment by cygnusv** [comment]
Haven't seen something like this in a while. We can re-open if it happens again
