### ISSUE TITLE
Another unhandled background error.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2349]
```
Unhandled error during node learning.  Attempting graceful crash.
Unhandled Error
Traceback (most recent call last):
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
    f(*a, **kw)
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/network/nodes.py", line 502, in _crash_gracefully
    failure.raiseException()
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/network/nodes.py", line 562, in _discover_or_abort
    result = self.learn_from_teacher_node(eager=False, canceller=self._discovery_canceller)
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/network/nodes.py", line 805, in learn_from_teacher_node
    except current_teacher.InvalidNode as e:
  File "/home/jmyles/projects/nucypher/bytestringSplitter/bytestring_splitter/__init__.py", line 77, in __getattr__
    raise AttributeError(
builtins.AttributeError: <class 'nucypher.network.nodes.NodeSprout'> doesn't have a InvalidNode, and it's not a partially split object either; those are ['domain', 'interface_signature', 'decentralized_identity_evidence', 'verifying_key', 'encrypting_key', 'certificate', 'rest_interface']
```

**Comment by KPrasch** [comment]
This issue has not been seen or reproduced recently.  Closing.
