### ISSUE TITLE
nucypher ursula run --worker-address causes invalid checksum exception

### ISSUE THREAD

**Issue by TuFoZo** [nucypher/nucypher#2374]
Executing `nucypher ursula run --worker-address `causes invalid checksum exception error even if the address provided in the command line is checksummed.

Steps to reproduce the behavior
1. Make sure that the worker_address in ursula.json points to the checksum eth worker addr (ETH_checksummed_addr)
2. Execute `nucypher ursula run --worker_address ETH_checksummed_addr`

`nucypher ursula run --worker-address ETH_checksummed_addr --provider https://mainnet.infura.io/v3/xyz --network mainnet`

Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nucypher/cli/commands/ursula.py", line 377, in run
    config_file = select_config_file(emitter=emitter,
  File "/usr/local/lib/python3.8/dist-packages/nucypher/cli/actions/select.py", line 261, in select_config_file
    parsed_addresses = {config_class.checksum_address_from_filepath(fp): fp for fp in config_files}
  File "/usr/local/lib/python3.8/dist-packages/nucypher/cli/actions/select.py", line 261, in <dictcomp>
    parsed_addresses = {config_class.checksum_address_from_filepath(fp): fp for fp in config_files}
  File "/usr/local/lib/python3.8/dist-packages/nucypher/config/node.py", line 285, in checksum_address_from_filepath
    raise RuntimeError(f"Invalid checksum address detected in configuration file at '{filepath}'.")
RuntimeError: Invalid checksum address detected in configuration file at '/home/<home>/.local/share/nucypher/ursula.json'.

Reproduced on the following system:
 - OS Version:  Ubuntu 20.04.1 LTS
 - Nucypher Version:  4.0.1
-  geth 1.9.23

**Comment by KPrasch** [comment]
The issue described by the traceback is actually that the worker address inside the node's configuration file is invalid, not the flag.
```
RuntimeError: Invalid checksum address detected in configuration file at '/home//.local/share/nucypher/ursula.json'.
 ```

 While I do expect the `--worker-address` flag to override and file-based configuration values for, they still must be valid in order to run properly.

To fix this issue you can run `nucypher ursula config --worker-address <CHECKSUMMED ETH ADDRESS>`, then try again.
