### ISSUE TITLE
Ursula comes up but exits later on status command if TZ and /etc/localtime unset

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2386]
Nucypher worker was started with an interactive console in a minimal system container (Alpine Linux docker image) which had neither TZ set in the environment nor was `/etc/localtime` set to a timezone file.

The Ursula worker came up and started normally, however issuing the `status` command at the console then caused it to abruptly terminate with an exception below.

Setting `TZ=UTC` in the environment was effective as a workaround however any issues with the running system environment (such as timezone) should be detected at startup and cause an immediate exit rather than be allowed to linger and bring down a node after it has been running for some time.

From the stack trace it appears the pendulum/datetime package caused the issue when obtaining a local timestamp - I would suggest calling now() in a system environment sanity check function prior to the worker entering its long running service loop to force the check.
```
Ursula(0x559A040) >>> status
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python3.8/site-packages/twisted/internet/process.py", line 252, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/usr/lib/python3.8/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/usr/lib/python3.8/site-packages/twisted/internet/process.py", line 256, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/usr/lib/python3.8/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/usr/lib/python3.8/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3.8/site-packages/nucypher/cli/processes.py", line 138, in lineReceived
    self.__commands[line]()
  File "/usr/lib/python3.8/site-packages/nucypher/cli/processes.py", line 112, in paintStatus
    paint_node_status(emitter=self.emitter, ursula=self.ursula, start_time=self.start_time)
  File "/usr/lib/python3.8/site-packages/nucypher/cli/painting/nodes.py", line 67, in paint_node_status
    'Start Time .......... {}'.format(start_time.slang_time()),
  File "/usr/lib/python3.8/site-packages/maya/core.py", line 366, in slang_time
    return pendulum.instance(dt).diff_for_humans(locale=locale)
  File "/usr/lib/python3.8/site-packages/pendulum/datetime.py", line 824, in diff_for_humans
    other = self.now()
  File "/usr/lib/python3.8/site-packages/pendulum/datetime.py", line 106, in now
    return pendulum.now(tz)
  File "/usr/lib/python3.8/site-packages/pendulum/__init__.py", line 211, in now
    dt = _datetime.datetime.now(local_timezone())
  File "/usr/lib/python3.8/site-packages/pendulum/tz/__init__.py", line 60, in local_timezone
    return get_local_timezone()
  File "/usr/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 35, in get_local_timezone
    tz = _get_system_timezone()
  File "/usr/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 63, in _get_system_timezone
    return _get_unix_timezone()
  File "/usr/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 242, in _get_unix_timezone
    raise RuntimeError("Unable to find any timezone configuration")
builtins.RuntimeError: Unable to find any timezone configuration
```

**Comment by derekpierre** [comment]
Interactive console has been deprecated.
