### ISSUE TITLE
Ursula exited on exception (NodeSprout w/o rest_url) when known_nodes command issued

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2387]
Mainnet ursula worker exited abruptly when `known_nodes` command was entered into interactive console.

Stack trace below suggests a `NodeSprout` instance was lacking a `rest_url` property that it should have had.
```
Ursula(0x559A040) >>> known_nodes

Known Nodes (connected 1218 / seen 57)
Fleet State fa1ca57 ⇀Gold Yankee↽ [Y]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python3.8/site-packages/twisted/internet/process.py", line 252, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/usr/lib/python3.8/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/usr/lib/python3.8/site-packages/twisted/internet/process.py", line 256, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/usr/lib/python3.8/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/usr/lib/python3.8/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3.8/site-packages/nucypher/cli/processes.py", line 138, in lineReceived
    self.__commands[line]()
  File "/usr/lib/python3.8/site-packages/nucypher/cli/processes.py", line 95, in paintKnownNodes
    paint_known_nodes(emitter=self.emitter, ursula=self.ursula)
  File "/usr/lib/python3.8/site-packages/nucypher/cli/painting/nodes.py", line 138, in paint_known_nodes
    emitter.echo(row_template.format(node.rest_url().ljust(20), node), color=color_index[node_type])
  File "/usr/lib/python3.8/site-packages/bytestring_splitter/__init__.py", line 76, in __getattr__
    raise AttributeError(f"{self.__class__} doesn't have a {message_name}, and it's not a partially split object either; those are {list(self.processed_objects.keys())}")
builtins.AttributeError: <class 'nucypher.network.nodes.NodeSprout'> doesn't have a rest_url, and it's not a partially split object either; those are ['domain', 'interface_signature', 'decentralized_identity_evidence', 'verifying_key', 'encrypting_key', 'certificate', 'rest_interface']
```

**Comment by cygnusv** [comment]
Thanks for reporting this! This is a known issue (#2238), and tangentially related to #2356
