### ISSUE TITLE
Ursula worker unhandled error during node learning and stack trace

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2394]
Mainnet ursula worker printed the following unhandled error and stack trace earlier today.
The process is currently still running and it returns a seemingly valid /status page when queried on port 9151.
It's not clear to me if the node is still functioning normally or if part of it has failed to recover.
The Nucypher version was 4.0.1.

```
Starting services...
✓ Database pruning
✓ Work Tracking
✓ Prometheus Exporter

Type 'help' or '?' for help
Starting Ursula on 144.76.180.219:9151
Working ~ Keep Ursula Online!
Ursula(0x436c9bc) >>>
Broadcasting COMMITTONEXTPERIOD Transaction (0.006406624839076308 ETH @ 18.881554818 gwei)...
Broadcasting COMMITTONEXTPERIOD Transaction (0.006945536084849536 ETH @ 20.810096192 gwei)...
Broadcasting COMMITTONEXTPERIOD Transaction (0.006187213519602444 ETH @ 22.059689669 gwei)...
Unhandled error during node learning.  Attempting graceful crash.
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nucypher/characters/lawful.py", line 1283, in run
    deployer.run()  # <--- Blocking Call (Reactor)
  File "/usr/lib/python3.8/site-packages/hendrix/deploy/base.py", line 186, in run
    self.reactor.run()
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
    f(*a, **kw)
  File "/usr/lib/python3.8/site-packages/nucypher/network/nodes.py", line 502, in _crash_gracefully
    failure.raiseException()
  File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3.8/site-packages/nucypher/network/nodes.py", line 560, in _discover_or_abort
    result = self.learn_from_teacher_node(eager=False, canceller=self._discovery_canceller)
  File "/usr/lib/python3.8/site-packages/nucypher/network/nodes.py", line 836, in learn_from_teacher_node
    self.verify_from(current_teacher, node_payload, signature=signature)
  File "/usr/lib/python3.8/site-packages/nucypher/characters/base.py", line 457, in verify_from
    node_on_the_other_end = self.known_node_class.from_seednode_metadata(stranger.seed_node_metadata(),
  File "/usr/lib/python3.8/site-packages/nucypher/characters/lawful.py", line 1395, in from_seednode_metadata
    return cls.from_seed_and_stake_info(seed_uri=seed_uri, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/nucypher/characters/lawful.py", line 1454, in from_seed_and_stake_info
    certificate = network_middleware.get_certificate(host=host, port=port)
  File "/usr/lib/python3.8/site-packages/nucypher/network/middleware.py", line 177, in get_certificate
    seednode_certificate = ssl.get_server_certificate(addr=(host, port))
  File "/usr/lib/python3.8/ssl.py", line 1483, in get_server_certificate
    with  create_connection(addr) as sock:
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
builtins.ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by cygnusv** [comment]
Not related to your issue, but note released a new version of nucypher earlier today that fixes the problem of multiple commitment TXs. It seems your node made 3 of those.

**Comment by svenski123** [comment]
Actually no - the node had been up a few days and those transactions were on separate days (I haven't specified a  gas strategy so I assume it's running with fast i.e premium unleaded / 98).

In any event I've just upgraded to 4.1.0.

**Comment by KPrasch** [comment]
While I cannot easily point to a specific PR that closes this issue, I have not seen this kind of behavior in version 4.5+.  Instead, when a worker node encounters a downed peer, it simply logs the result and moves on.

@svenski123 - Are you still experiencing this issue?

**Comment by svenski123** [comment]
No I haven't seen this for some time now.
