### ISSUE TITLE
Replacement transaction underpriced

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2398]
**Describe the Bug**
It seems we should increase the gas price for replacement TXs

**To Reproduce**
TBD

**Traceback or Screenshots (Optional) **
```
Unhandled error during node work tracking. <twisted.python.failure.Failure builtins.ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}>
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, call.kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in call
    d = defer.maybeDeferred(self.f, *self.a, self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
    f(a, **kw)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 608, in _crash_gracefully
    failure.raiseException()
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(args, kw)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 715, in _do_work
    self.handle_replacement_commitment(current_block_number=current_block_number)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 701, in handle_replacement_commitment
    tx_firing_block_number=tx_firing_block_number)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 680, in fire_replacement_commitment
    replacement_txhash = self.fire_commitment()  # replace
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/token.py", line 756, in __fire_commitment
    txhash = self.worker.commit_to_next_period(fire_and_forget=True)  # < --- blockchain WRITE
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 116, in wrapped
    return func(actor, *args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 124, in wrapped
    receipt_or_txhash = actor_method(self, args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/actors.py", line 1612, in commit_to_next_period
    fire_and_forget=fire_and_forget)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/agents.py", line 589, in commit_to_next_period
    fire_and_forget=fire_and_forget)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/interfaces.py", line 685, in send_transaction
    fire_and_forget=fire_and_forget)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/interfaces.py", line 605, in sign_and_broadcast_transaction
    txhash = self.client.send_raw_transaction(signed_raw_transaction)  # <--- BROADCAST
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/clients.py", line 398, in send_raw_transaction
    return self.w3.eth.sendRawTransaction(transaction_bytes)
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 395, in sendRawTransaction
    [raw_transaction],
  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
builtins.ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
```

**System (please complete the following information):**
 - OS Version:
 - Nucypher Version:
 - Ethereum Node Version:

**Comment by BisonAl** [comment]
I've been seeing this too @cygnusv, from what we've seen there's about a ~2% chance daily a node can throw this message  fail to commit to the next round as a result.

**Comment by vepkenez** [comment]
It is possibly true that Ursula crashing and restarting would be the best way to handle these situations.  It depends on the prevalence of “auto restart” among the fleet.

**Comment by KPrasch** [comment]
@BisonAl 

> ... otherwise it'll just idle and stop earning rewards

Are you certain this is the behavior?  Ursula is aiming to never crash and continue - I expect it to simply retry and continue.

**Comment by BisonAl** [comment]
> Are you certain this is the behavior?

From what we've observed yes Kprasch, every time I've seen an ursula get into this state the only remediation is restarting the process - otherwise it will indefinitely fail to commit to the next round. Has occurred 3-4 times at this point in the last week, across a number of our nodes.

> Ursula is aiming to never crash - I expect it to simply retry and continue.

Yeah perhaps prescribing a crash on these request failures may not be the best route for most users, so probably doesn't need to be addressed. However it does not seem to simply retry and continue as it is now, instead just getting stuck and falling out of the active set of workers.

**Comment by KPrasch** [comment]
Okay - Thanks for the quick response!  Sounds like this `ValueError` may not be handled properly along with the rest of the failure modes for some reason.  Sounds like a separate issue - opened https://github.com/nucypher/nucypher/issues/2405

**Comment by cygnusv** [comment]
A related error is `{'code': -32000, 'message': 'already known'}`.
There's no documentation about this, but after checking geth's code it seems you can get this when trying to send a TX with a hash that's the identical to another TX in the mempool (i.e., you're sending the exact same TX). In our context, this means that sometimes we fire a replacement transaction with the same nonce and gas price. 

In order to get rid of both errors (`'replacement transaction underpriced'` and `'already known'`), if we're sending a replacement TX (i.e., same nonce), we need to ensure we provide a higher gas price.

**Comment by cygnusv** [comment]
The problem with tweaking the gas price as a workaround for this error is that it can can interfere with both the gas strategy and max gas price set in the configuration. In other words, there's no way to definitely get rid of this error without breaking the assumption that new TXs are going to respect the gas strategies and/or max gas price.

Marking this as `wontfix`
