### ISSUE TITLE
Prevent solc compile modules from being imported from standard installation

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2455]
Imports to `nucypher.blockchain.eth.sol.compile`  can be avoided entirely for standard installations:

```
Successfully installed nucypher-4.2.1
(nucypher-venv) nuacc@NuCypherAR:~$ nucypher --version
Traceback (most recent call last):
  File "/home/nuacc/nucypher-venv/bin/nucypher", line 5, in <module>
    from nucypher.cli.main import nucypher_cli
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/main.py", line 20, in <module>
    from nucypher.cli.commands import (
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/alice.py", line 24, in <module>
    from nucypher.characters.control.interfaces import AliceInterface
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/characters/control/interfaces.py", line 23, in <module>
    from nucypher.characters.control.specifications import alice, bob, enrico
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/characters/control/specifications/alice.py", line 21, in <module>
    from nucypher.characters.control.specifications import fields
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/characters/control/specifications/fields/__init__.py", line 24, in <module>
    from nucypher.characters.control.specifications.fields.misc import *
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/characters/control/specifications/fields/misc.py", line 23, in <module>
    from nucypher.cli import types
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/types.py", line 23, in <module>
    from nucypher.blockchain.eth.interfaces import BlockchainInterface
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 61, in <module>
    from nucypher.blockchain.eth.sol.compile.compile import multiversion_compile
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/sol/compile/compile.py", line 26, in <module>
    from nucypher.blockchain.eth.sol.compile.aggregation import merge_contract_outputs
  File "/home/nuacc/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/sol/compile/aggregation.py", line 20, in <module>
    from re import Pattern
ImportError: cannot import name 'Pattern'
```

**Comment by cygnusv** [comment]
We import this module in `nucypher.blockchain.eth.interfaces.py`:

```python
from nucypher.blockchain.eth.sol.compile.compile import multiversion_compile
from nucypher.blockchain.eth.sol.compile.constants import SOLIDITY_SOURCE_ROOT
from nucypher.blockchain.eth.sol.compile.types import SourceBundle
```

Maybe we can just close this issue? What do you think @KPrasch?

**Comment by KPrasch** [comment]
obsoleted by migration to eth-ape.
