### ISSUE TITLE
cloudworkers: unexpected kwarg 'config_file'

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2473]
**Describe the Bug**

Unhandled exception encountered when adding a cloudworker (home office example)

**To Reproduce**
```
$ nucypher cloudworkers add_for_stake --staker-address 0xdeadbeef --host-address 192.168.1.xxx --login-name x --key-path ~/.ssh/id_rsa
```

**Traceback**
```
Traceback (most recent call last):
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/bin/nucypher", line 33, in <module>
    sys.exit(load_entry_point('nucypher', 'console_scripts', 'nucypher')())
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/k/Git/nucypher/nucypher/cli/options.py", line 167, in wrapper
    return func(**kwargs)
  File "/home/k/Git/nucypher/nucypher/cli/options.py", line 167, in wrapper
    return func(**kwargs)
  File "/home/k/Git/nucypher/nucypher/cli/options.py", line 167, in wrapper
    return func(**kwargs)
TypeError: add_for_stake() got an unexpected keyword argument 'config_file'

```

**System (please complete the following information):**
 - OS Version: Ubuntu 20.04
 - Nucypher Version: 4.3.0
 - Ethereum Node Version:  Infura

**Comment by KPrasch** [comment]
Closed by #2475
