### ISSUE TITLE
Remove prometheus WL metrics collectors for Lynx testnet

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2545]

**Comment by BisonAl** [comment]
Example error logs from an ursula on the `lynx` testnet running with the `--prometheus` flag:
```
Authenticating Ursula
Qualifying worker
✓ Worker is bonded to 0xSecretEthereumAddress
✓ Worker is funded with 4.999889882124843647 ETH
✓ External IP matches configuration
Starting services
✓ Database Pruning
✓ Work Tracking
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 1730, in get_agent
    return cast(Agent, cls.__agents[registry_id][agent_class])
KeyError: <class 'nucypher.blockchain.eth.agents.WorkLockAgent'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/commands/ursula.py", line 393, in run
    URSULA.run(emitter=emitter,
  File "/usr/local/lib/python3.8/site-packages/nucypher/characters/lawful.py", line 1314, in run
    start_prometheus_exporter(ursula=self, prometheus_config=prometheus_config)
  File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/prometheus/metrics.py", line 158, in start_prometheus_exporter
    metrics_collectors = create_metrics_collectors(ursula, prometheus_config.metrics_prefix)
  File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/prometheus/metrics.py", line 210, in create_metrics_collectors
    worklock_events_collectors = create_worklock_events_metric_collectors(ursula=ursula,
  File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/prometheus/metrics.py", line 295, in create_worklock_events_metric_collectors
    worklock_agent = ContractAgency.get_agent(WorkLockAgent, registry=ursula.registry)
  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 1732, in get_agent
    agent = cast(Agent, agent_class(registry=registry, provider_uri=provider_uri))
  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 113, in __init__
    contract = self.blockchain.get_contract_by_name(
  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 667, in get_contract_by_name
    target_contract_records = registry.search(contract_name=contract_name, contract_version=contract_version)
  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/registry.py", line 334, in search
    raise self.UnknownContract(contract_name)
nucypher.blockchain.eth.registry.UnknownContract: WorkLock
stream closed
```
