### ISSUE TITLE
KeyboardInterrupt of worker results in errors

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2608]
**Describe the Bug**
Stopping a running node process results in two exceptions instead of gracefully exiting.

**To Reproduce**
Stop a running node with CTRL+C

**Traceback or Screenshots (Optional)**
```
^CUnhandled Error
Traceback (most recent call last):
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/python/threadpool.py", line 278, in stop
    self._team.quit()
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/_threads/_team.py", line 226, in quit
    self._quit.set()
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/_threads/_convenience.py", line 35, in set
    self.check()
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
    raise AlreadyQuit()
twisted._threads._ithreads.AlreadyQuit: 

Traceback (most recent call last):
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/bin/nucypher", line 33, in <module>
    sys.exit(load_entry_point('nucypher', 'console_scripts', 'nucypher')())
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/k/Git/nucypher-ibex/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/home/k/Git/nucypher-ibex/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/home/k/Git/nucypher-ibex/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/home/k/Git/nucypher-ibex/nucypher/cli/commands/ursula.py", line 392, in run
    preflight=not dev_mode)
  File "/home/k/Git/nucypher-ibex/nucypher/characters/lawful.py", line 1346, in run
    reactor.run()  # <--- Blocking Call (Reactor)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/base.py", line 1282, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/base.py", line 1262, in startRunning
    ReactorBase.startRunning(self)
  File "/home/k/.local/share/virtualenvs/nucypher-ibex-HOw7kB0y/lib/python3.7/site-packages/twisted/internet/base.py", line 765, in startRunning
    raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable

```

**System (please complete the following information):**
 - OS Version: ubuntu
 - Nucypher Version: 4.7.1
 - Ethereum Node Version:  N/A

**Comment by piotr-roslaniec** [comment]
The second exception is caused by this [change](https://github.com/piotr-roslaniec/nucypher/blob/264aa1e360691efb5f398f8c1f37efaa08d89eeb/nucypher/characters/lawful.py#L1345).

**Comment by KPrasch** [comment]
> The second exception is caused by this change.

@piotr-roslaniec Oh my how did you track this down?  I'll be very happy when this error is resolved, it's so noisy!
