### ISSUE TITLE
`nucypher staker status` crashes with non-staking account

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2642]
**Describe the Bug**
`nucypher staker status` raises an unhandled exception with non-staking account as input.

**To Reproduce**
```
nucypher status stakers --network mainnet --provider ... --staking-address <NOT A STAKING ACCOUNT> --substakes
```

**Traceback or Screenshots (Optional)**
```
Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/bin/nucypher", line 33, in <module>
    sys.exit(load_entry_point('nucypher', 'console_scripts', 'nucypher')())
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/options.py", line 169, in wrapper
    return func(**kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/commands/status.py", line 136, in stakers
    paint_stakes(emitter=emitter, staker=staker, paint_unlocked=True)
  File "/home/kieran/Git/nucypher/nucypher/cli/painting/staking.py", line 69, in paint_stakes
    missing = staker.missing_commitments
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/actors.py", line 1003, in missing_commitments
    missing = self.staking_agent.get_missing_commitments(checksum_address=staker_address)
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/home/kieran/Git/nucypher/nucypher/blockchain/eth/agents.py", line 741, in get_missing_commitments
    initial_staking_period = min(stakes, key=lambda s: s[0])[0]
ValueError: min() arg is an empty sequence

```

**System (please complete the following information):**
 - OS Version: ubuntu 20.04
 - Nucypher Version: 5.0.0
 - Ethereum Node Version:  Infura

**Comment by KPrasch** [comment]
Closed by #2867
