### ISSUE TITLE
Running 'nucypher status pre' crashes the CLI

### ISSUE THREAD

**Issue by KevinVitale** [nucypher/nucypher#2900]
**Describe the Bug**
`nucypher status pre` **requires** `--staking-provider`; however, when providing a value, it crashes the CLI application.

**To Reproduce**
Run:
```
$ nucypher status pre --eth-provider [IPC-ENDPOINT] --staking-provider [ETH-ADDRESS]
```

**Traceback or Screenshots (Optional)**

```sh
Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
TypeError: staking_providers() got an unexpected keyword argument 'staking_provider'
```

**System (please complete the following information):**
 - OS Version: recent Ubuntu LTS
 - Nucypher Version: 6
 - Ethereum Node Version:  latest geth

**Comment by derekpierre** [comment]
Unclear that this functionality is still needed - probably not, and the `nucypher status pre` command should be removed.

**Comment by KPrasch** [comment]
We've decided to no longer support the `nucypher status pre` CLI.
