### ISSUE TITLE
`prometheus` not correctly supported in v6.0.0 - either update prometheus functionality or remove flag

### ISSUE THREAD

**Issue by hypnotortoise** [nucypher/nucypher#2905]
**Describe the Bug**
Node crashes after startup with dependency issues when prometheus support is enabled in v6.

**To Reproduce**
Start node with `--prometheus` flag.

**Traceback or Screenshots (Optional)**
Docker logs from Ursula Node:
```
....
Starting services
✓ Node Discovery (Mainnet)
...
Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/nucypher/cli/commands/ursula.py", line 438, in run
    URSULA.run(emitter=emitter,
  File "/usr/local/lib/python3.8/site-packages/nucypher/characters/lawful.py", line 955, in run
    start_prometheus_exporter(ursula=self, prometheus_config=prometheus_config)
  File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/prometheus/metrics.py", line 155, in start_prometheus_exporter
    metrics_collectors = create_metrics_collectors(ursula, prometheus_config.metrics_prefix)
  File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/prometheus/metrics.py", line 200, in create_metrics_collectors
    staking_events_collectors = create_staking_events_metric_collectors(ursula=ursula,
  File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/prometheus/metrics.py", line 222, in create_staking_events_metric_collectors
    contract_agent_class=StakingEscrowAgent,
NameError: name 'StakingEscrowAgent' is not defined
```

**System (please complete the following information):**
 - OS Version: Linux
 - Nucypher Version: 6.0.0
 - Ethereum Node Version:  latest Geth

**Comment by derekpierre** [comment]
`prometheus` is not currently supported in v6.0.0 - something we need to add/update.

At the very least, if we don't support it in the next release, we'll remove the ability to use the flag.
