### ISSUE TITLE
Unhandled Error in Deferred.docker log of running node

### ISSUE THREAD

**Issue by deeP-2323** [nucypher/nucypher#2922]
**Describe the Bug**
While PRE node is running, occasionally receiving Unhandled error in Deferred:

**To Reproduce**
run PRE node using Docker.

**Traceback or Screenshots (Optional)**
This is one sample (IP address omitted)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 661, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/nodes.py", line 607, in _discover_or_abort
    result = self.learn_from_teacher_node(eager=False, canceller=self._discovery_canceller)
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/nodes.py", line 799, in learn_from_teacher_node
    response = self.network_middleware.get_nodes_via_rest(node=current_teacher,
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/middleware.py", line 266, in get_nodes_via_rest
    response = self.client.post(node_or_sprout=node,
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/middleware.py", line 147, in method_wrapper
    host, port, http_client = self.verify_and_parse_node_or_host_and_port(node_or_sprout, host, port)
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/middleware.py", line 102, in verify_and_parse_node_or_host_and_port
    node.verify_node(network_middleware_client=self, registry=self.registry, eth_provider_uri=self.eth_provider_uri)
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/nodes.py", line 1159, in verify_node
    response_data = network_middleware_client.node_information(host=self.rest_interface.host,
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/middleware.py", line 129, in node_information
    response = self.get(node_or_sprout=EXEMPT_FROM_VERIFICATION,
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/middleware.py", line 155, in method_wrapper
    raise RestMiddleware.Unreachable(message=f'Node {node_or_sprout} {host}:{port} is unreachable: {e}')
nucypher.network.middleware.Unreachable: Node EXEMPT_FROM_VERIFICATION <omitted IP address> is unreachable: No response from <omitted IP>

```
**System (please complete the following information):**
 - OS Version: Ubuntu 20.04.4 LTS 
 - Nucypher Version: 6.0 current
 - Ethereum Node Version:  current

**Comment by derekpierre** [comment]
Related to #2920 .

**Comment by KPrasch** [comment]
This is normal and expected behavior when contacting a peer that is offline.  If your node continues to run, carry on!
