### ISSUE TITLE
command `nucypher status events` return error

### ISSUE THREAD

**Issue by rk-p2p** [nucypher/nucypher#2931]
**Describe the Bug**
Trying to get events with command below and got error. Is it working or it's deprecated?

**To Reproduce**
`nucypher status events --eth-provider https://mainnet.infura.io/v3/KEY`

**Traceback or Screenshots (Optional)**
```
Reading Latest Chaindata...
Retrieving events from block 14673032 to latest
Traceback (most recent call last):
  File "/home/ursula/nucypher-venv/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/options.py", line 187, in wrapper
    return func(**kwargs)
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/nucypher/cli/commands/status.py", line 224, in events
    agent = ContractAgency.get_agent_by_contract_name(
  File "/home/ursula/nucypher-venv/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 610, in get_agent_by_contract_name
    agent_class: Type[EthereumContractAgent] = getattr(agents_module, agent_name)
AttributeError: module 'nucypher.blockchain.eth.agents' has no attribute 'SimplePREApplicationAgent'
```

**System (please complete the following information):**
 - OS Version: Ubuntu 20.04.4 LTS
 - Nucypher Version: 6.0.0
 - Ethereum Node Version: Infura API

**Comment by derekpierre** [comment]
Thanks for filing, this should be fixed once #2934 is merged. It will be fixed for v6.1.0. If you want to use the updated code in the interim, you can pull it from the PR branch.
