### ISSUE TITLE
Traceback on operator running

### ISSUE THREAD

**Issue by rk-p2p** [nucypher/nucypher#2938]
**Describe the Bug**
Got tracebacks when operator is running

**To Reproduce**
Simply start systemd unit with bonded operator and wait.
`/home/nucypher/nucypher-venv/bin/nucypher ursula run --verbose`

**Traceback or Screenshots (Optional)**
```
...
May 05 23:30:20 nucypher[45383]: builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
May 05 23:30:20 nucypher[45383]: Traceback (most recent call last):
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/protocols/basic.py", line 549, in dataReceived
May 05 23:30:20 nucypher[45383]:     why = self.lineReceived(line)
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/http.py", line 2244, in lineReceived
May 05 23:30:20 nucypher[45383]:     self.allContentReceived()
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/http.py", line 2370, in allContentReceived
May 05 23:30:20 nucypher[45383]:     req.requestReceived(command, path, version)
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/http.py", line 1003, in requestReceived
May 05 23:30:20 nucypher[45383]:     self.process()
May 05 23:30:20 nucypher[45383]: --- <exception caught here> ---
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/server.py", line 222, in process
May 05 23:30:20 nucypher[45383]:     resrc = self.site.getResourceFor(self)
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/server.py", line 891, in getResourceFor
May 05 23:30:20 nucypher[45383]:     return resource.getChildForRequest(self.resource, request)
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/resource.py", line 97, in getChildForRequest
May 05 23:30:20 nucypher[45383]:     resource = resource.getChildWithDefault(pathElement, request)
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/twisted/web/resource.py", line 199, in getChildWithDefault
May 05 23:30:20 nucypher[45383]:     return self.getChild(path, request)
May 05 23:30:20 nucypher[45383]:   File "/home/nucypher/nucypher-venv/lib/python3.8/site-packages/hendrix/facilities/resources.py", line 56, in getChild
May 05 23:30:20 nucypher[45383]:     path = path.decode('utf-8')
May 05 23:30:20 nucypher[45383]: builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
```

**System (please complete the following information):**
 - OS Version: Ubuntu 20.04.4 LTS
 - Nucypher Version: 6.0.0
 - Ethereum Node Version: Infura API

**Comment by rk-p2p** [comment]
@KPrasch @derekpierre

**Comment by derekpierre** [comment]
Anything else you can tell us about the circumstances, or after effects of this traceback. Did the node crash after this traceback, or did it continue running as normal?

Since `--verbose` is specified, it's possible that one of the node's server endpoints received invalid bytes as input, logged the exception and the node just continued on its merry way. If this is the case it would seemingly not be a bug  (at least not an obvious one) but rather the correct handling of invalid input.

**Comment by rk-p2p** [comment]
Yea, node continue running after this traceback.

**Comment by derekpierre** [comment]
With `verbose` on you'll get some of these log messages that are usually never shown by default. I'll close for now, but if the node starts acting weirdly and you think this influenced that behaviour, you can reopen.
