### ISSUE TITLE
Porter can unintentionally mutate conditions

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#3012]
## Summary

This is a two-part issue to follow-up #3002 which unintentionally introduced incompatibility with `nucypher/nucypher-ts` and/or `nucypher/tdec-nft-example` and illuminates a preexisting unhanded exception.

## Part One

The `functionAbi` field of condition JSON no longer accepts a list or full contract ABI to be deserialized.   As a result when Ursula attempts to deserialze the condition containing a full contract ABI as a list, Marshmallow validation fails and bubbles up as an unhanded exception.  

Here's a relayed error from porter as an example:

```
Some Ursulas have failed with errors:
0x48C8039c32F4c6f5cb206A5911C8Ae814929C16B - UnexpectedResponse: b'<!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

There are a few potential mitigations and improvements inside nucypher/nucypher:

1. Handle Marshmallow deserialization errors with a useful error message and avoid issuing a 500.
2. Do not permit both the `function_abi` and the `standard_contract_type` to both be present in the same condition (https://marshmallow.readthedocs.io/en/stable/extending.html#raising-errors-in-pre-post-processor-methods)
3. ~~Reconsider allowing `function_abi` to be a `fields.List` or a `fields.Dict` in `ContractCondition.Schema` - is requiring a dict too strict?~~ We've decided to keep function abi enforcement as a dict, and thus a single function.

## Part Two

Somehow conditions generated by the NFT example and/or nucypher-ts become populated with a full contract ABI.

##### To Reproduce

Generate a condition using the NFT demo deployed here and submit a decryption request
https://deploy-preview-7--tdec-nft-example.netlify.app/

##### Condition displayed in the NFT preview

This is the condition displayed by `nucypher/tdec-nft-demo` in the UIs preview area:

```json
{
  "contractAddress": "0x00000000006c3852cbef3e08e8df289169ede581",
  "chain": 80001,
  "standardContractType": "ERC721",
  "method": "ownerOf",
  "parameters": [
    997
  ],
  "returnValueTest": {
    "comparator": "==",
    "value": ":userAddress"
  }
}
```

##### Condition actually submitted in the request 

Here's a retrieval kit I intercepted in the browser's debugger:

```
UktpdAABAAGTxGICXUXnV5SxLnMravWJsiix0BTBZKEFQ01nzRRoOWXdoJcDSt3BwqdPmZaxcqeUJpBreSFvv5sGNFGEOxeWZPxHyWA62hyIs3QHPsCh4o4Vqqt+P8JwctXo/guCQ16i8kUUf5DZ01t7ImNvbnRyYWN0QWRkcmVzcyI6IjB4MDAwMDAwMDAwMDZjMzg1MmNiZWYzZTA4ZThkZjI4OTE2OWVkZTU4MSIsImNoYWluIjo4MDAwMSwic3RhbmRhcmRDb250cmFjdFR5cGUiOiJFUkM3MjEiLCJtZXRob2QiOiJvd25lck9mIiwicGFyYW1ldGVycyI6Wzk5N10sInJldHVyblZhbHVlVGVzdCI6eyJjb21wYXJhdG9yIjoiPT0iLCJ2YWx1ZSI6Ijp1c2VyQWRkcmVzcyJ9fV0=
```

Decoded base 64 reveals the conditions:

```
b'RKit\x00\x01\x00\x01\x93\xc4b\x02]E\xe7W\x94\xb1.s+j\xf5\x89\xb2(\xb1\xd0\x14\xc1d\xa1\x05CMg\xcd\x14h9e\xdd\xa0\x97\x03J\xdd\xc1\xc2\xa7O\x99\x96\xb1r\xa7\x94&\x90ky!o\xbf\x9b\x064Q\x84;\x17\x96d\xfcG\xc9`:\xda\x1c\x88\xb3t\x07>\xc0\xa1\xe2\x8e\x15\xaa\xab~?\xc2pr\xd5\xe8\xfe\x0b\x82C^\xa2\xf2E\x14\x7f\x90\xd9\xd3[{"contractAddress":"0x00000000006c3852cbef3e08e8df289169ede581","chain":80001,"standardContractType":"ERC721","method":"ownerOf","parameters":[997],"returnValueTest":{"comparator":"==","value":":userAddress"}}]'
```

However this intercepted data that is somehow received by Ursula at deserialization-time containing a full contract ABI.  **How did this happen?**

```JSON
 {'returnValueTest': {'value': ':userAddress', 'comparator': '=='}, 'functionAbi': "[{'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'approve', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'mint', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'}, {'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'safeTransferFrom', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'}, {'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}, {'internalType': 'bytes', 'name': '_data', 'type': 'bytes'}], 'name': 'safeTransferFrom', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'bool', 'name': 'approved', 'type': 'bool'}], 'name': 'setApprovalForAll', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'}, {'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'transferFrom', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'inputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'from', 'type': 'address'}, {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'}, {'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'Transfer', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'}, {'indexed': True, 'internalType': 'address', 'name': 'approved', 'type': 'address'}, {'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'Approval', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'}, {'indexed': True, 'internalType': 'address', 'name': 'operator', 'type': 'address'}, {'indexed': False, 'internalType': 'bool', 'name': 'approved', 'type': 'bool'}], 'name': 'ApprovalForAll', 'type': 'event'}, {'constant': True, 'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}], 'name': 'balanceOf', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'getApproved', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}, {'internalType': 'address', 'name': 'operator', 'type': 'address'}], 'name': 'isApprovedForAll', 'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}], 'name': 'ownerOf', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'bytes4', 'name': 'interfaceId', 'type': 'bytes4'}], 'name': 'supportsInterface', 'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}]", 'standardContractType': 'ERC721', 'chain': 80001, 'method': 'ownerOf', 'parameters': [997], 'contractAddress': '0x00000000006c3852cbEf3e08E8dF289169EdE581'}
```

##### Stack Trace

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/server.py", line 162, in reencrypt
    lingo = [ConditionLingo.from_list(lingo) if lingo else None for lingo in json_lingo]
  File "/usr/local/lib/python3.8/site-packages/nucypher/network/server.py", line 162, in <listcomp>
    lingo = [ConditionLingo.from_list(lingo) if lingo else None for lingo in json_lingo]
  File "/usr/local/lib/python3.8/site-packages/nucypher/policy/conditions/lingo.py", line 198, in from_list
    conditions = [_deserialize_condition_lingo(c) for c in payload]
  File "/usr/local/lib/python3.8/site-packages/nucypher/policy/conditions/lingo.py", line 198, in <listcomp>
    conditions = [_deserialize_condition_lingo(c) for c in payload]
  File "/usr/local/lib/python3.8/site-packages/nucypher/policy/conditions/_utils.py", line 104, in _deserialize_condition_lingo
    instance = lingo_class.from_dict(data)
  File "/usr/local/lib/python3.8/site-packages/nucypher/policy/conditions/base.py", line 50, in from_dict
    instance = schema.load(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'functionAbi': ['Not a valid mapping type.']}
```

**Comment by theref** [comment]
I like that `functionAbi` just takes a dictionary. You can just directly copy the abi from etherscan etc and paste it into the condition. Having to wrap it in a list or something feels like bad UX.

I think possibly both of your suggestion 1) and 2) would be good to implement.

**Comment by KPrasch** [comment]
After a deep debugging session @theref and I discovered that Porter parses conditions from retrieval kits, deserializes them into ConditionLingo and subsequently serializes them again.  In the process of doing so the abi resolution mechanism is called - since porter was deployed against an older version of the development branch, the full contract's ABI was populated.
