### ISSUE TITLE
`testnet_compound_multichain_taco` seems to be inconsistent

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3281]
Sometimes the script successfully executes, other times it fails due to a timeout (currently 10s).

```
Traceback (most recent call last):
  File "./examples/testnet_compound_multichain_taco.py", line 113, in <module>
    cleartext = bob.threshold_decrypt(threshold_message_kit=threshold_message_kit)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/characters/lawful.py", line 753, in threshold_decrypt
    decryption_shares = self._get_decryption_shares(
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/characters/lawful.py", line 675, in _get_decryption_shares
    raise Ursula.NotEnoughUrsulas(
nucypher.characters.lawful.NotEnoughUrsulas: Threshold of Ursulas unable to decrypt: {}
```

Seems to be a timeout issue but more investigation needed here. Consider value of timeout used, are we losing efficiency in our logic somewhere, etc.

Somewhat related to #3155 (though not related to PRE).

**Comment by derekpierre** [comment]
Related to #3283.

**Comment by derekpierre** [comment]
Lots of improvements related to decryption optimization. There is also a configurable timeout. This is now done.
