### ISSUE TITLE
`Invalid Transcript Aggregate` error blocks DKG tracker

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3526]
**Describe the Bug**
Nodes seem to be stuck in a retry loop after they see an `Invalid Transcript Aggregate`, which prevents them to process more DKG rituals until the one with the invalid aggregates timeouts.

**To Reproduce**
* Trigger DKG
* Force one of the nodes to submit a bad transcript (e.g., by using different validator keys than announced)
* Aggregation phase should get stuck at 0 aggregations.
* Trigger a second DKG, which won't be processed until the first timeouts.

**Traceback or Screenshots (Optional)**
```
2024-07-24T07:08:21-0700 [EventScannerTask#warn] Error during ritual event scanning: Traceback (most recent call last):
  File "/home/taco/.local/lib/python3.10/site-packages/twisted/internet/base.py", line 695, in run
    self.mainLoop()
  File "/home/taco/.local/lib/python3.10/site-packages/twisted/internet/base.py", line 705, in mainLoop
    self.runUntilCurrent()
  File "/home/taco/.local/lib/python3.10/site-packages/twisted/internet/base.py", line 1090, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/taco/.local/lib/python3.10/site-packages/twisted/internet/task.py", line 251, in __call__
    d = maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/taco/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 212, in maybeDeferred
    result = f(*args, **kwargs)
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 57, in run
    self.scanner()
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 453, in scan
    self.__scan(
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 424, in __scan
    result, total_chunks_scanned = self.scanner.scan(start_block, end_block)
  File "/home/taco/src/nucypher/nucypher/utilities/events.py", line 344, in scan
    actual_end_block, end_block_timestamp, new_entries = self.scan_chunk(current_block, estimated_end_block)
  File "/home/taco/src/nucypher/nucypher/utilities/events.py", line 246, in scan_chunk
    processed = self.process_event(event=evt, get_block_when=get_block_when)
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 40, in process_event
    hook(event, get_block_when)
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 415, in _handle_ritual_event
    d = self.__execute_action(ritual_event=ritual_event, timestamp=timestamp)
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 400, in __execute_action
    return task()
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/trackers/dkg.py", line 393, in task
    self.actions[event_type](timestamp=timestamp, **formatted_kwargs)
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/actors.py", line 685, in perform_round_2
    raise e
  File "/home/taco/src/nucypher/nucypher/blockchain/eth/actors.py", line 674, in perform_round_2
    ) = self.ritual_power.aggregate_transcripts(
  File "/home/taco/src/nucypher/nucypher/crypto/powers.py", line 319, in aggregate_transcripts
    aggregated_transcript, dkg_public_key = dkg.aggregate_transcripts(
  File "/home/taco/src/nucypher/nucypher/crypto/ferveo/dkg.py", line 64, in aggregate_transcripts
    verify_aggregate(pvss_aggregated, shares, validator_msgs)
  File "/home/taco/src/nucypher/nucypher/crypto/ferveo/dkg.py", line 74, in verify_aggregate
    pvss_aggregated.verify(shares, transcripts)
exceptions.InvalidTranscriptAggregate: 
```

**System (please complete the following information):**
 - OS Version:
 - Nucypher Version: v7.3.0
 - Ethereum Node Version:

**Comment by KPrasch** [comment]
Fixed in PR #3524
