### ISSUE TITLE
cannot import name 'ClassVar'

### ISSUE THREAD

**Issue by vmntruong** [nucypher/nucypher#398]
Hello. I am trying to run the first examples "finnegans-wake-federated.py" of the project in the folder "examples" using pipenv. I got this issue below  : 

> Traceback (most recent call last):
  File "finnegans-wake-federated.py", line 13, in <module>
    from nucypher.characters import Alice, Bob, Ursula
  File "/home/truong3/.local/share/virtualenvs/nucypher-O5RQWeHI/lib/python3.5/site-packages/nucypher-0.1-py3.5.egg/nucypher/characters.py", line 9, in <module>
ImportError: cannot import name 'ClassVar'

Please help! Thank you!

**Comment by KPrasch** [comment]
Hmm - Can you try running the demo with python 3.6?  

We Officially support python 3+ but I'd like to confirm this Issue is independent of your python version.
