### ISSUE TITLE
Gracefully Shutdown Running Nodes

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#412]

**Comment by KPrasch** [comment]
running the `stop` command in an interactive Ursula console results in (Alpha 20): 

```
Ursula(0x6B80fFe) >>> stop
Unhandled Error
Traceback (most recent call last):
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, args, **kw)
--- <exception caught here> ---
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(args, **kwargs)
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/python/threadpool.py", line 278, in stop
    self._team.quit()
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/_threads/_team.py", line 226, in quit
    self._quit.set()
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/_threads/_convenience.py", line 35, in set
    self.check()
  File "/home/mattharrop/nucypher/lib/python3.6/site-packages/twisted/_threads/_convenience.py", line 46, in check
    raise AlreadyQuit()
twisted._threads._ithreads.AlreadyQuit:

Stopping Ursula
Ursula Stopped
```

**Comment by tuxxy** [comment]
What about a non-interactive running Ursula (via systemd, etc)?

**Comment by tuxxy** [comment]
Closing this in favor of #1292
