### ISSUE TITLE
Pipenv graph fails with  "cannot import name 'get_installed_distributions'"

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#471]
```
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:04

To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

ERROR:  Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pipdeptree.py", line 17, in <module>
    from pip._internal import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pipdeptree.py", line 20, in <module>
    from pip import get_installed_distributions, FrozenRequirement
ImportError: cannot import name 'get_installed_distributions'

Exited with code 1
```

Looks like the Issue is die to incompatible version of `pip` and `pipenv` breaking `pipenv install`, `pipenv lock` (https://github.com/pypa/pipenv/issues/2924) and `pipenv graph` (see https://github.com/pypa/pip/issues/5154, https://github.com/pypa/pipenv/issues/2925) commands.

**Comment by KPrasch** [comment]
Installing `pip==18.0` fixes the installation Issue, and Until we have a better fix, I removed `pipenv graph` from our CI configuration.

**Comment by michwill** [comment]
I am guessing, this is fixed on `pipenv` side already?
