### ISSUE TITLE
Ursula CLI hangs with known_nodes command when there are no known_nodes

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#510]
```
Ursula >>> status

Ursula 0x<...redacted...>
--------------------------------------------------
Uptime: 0:02:49
Learning Round: 33
Operating Mode: Federated
Rest Interface <...redacted...>:9151
Node Storage Type Local:
Known Nodes: 0
Work Orders: 0

Ursula >>> known_nodes
Configured in Federated Only mode

Known Nodes (connected 0 / seen 0)           Last Seen    self   | known  | seednode | 

Unhandled Error
Traceback (most recent call last):
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/internet/process.py", line 291, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/internet/process.py", line 295, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/home/david/.local/share/virtualenvs/nucypher-rz58eSz8/lib/python3.6/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/home/david/NuCypher/dev/nucypher/nucypher/utilities/sandbox/ursula.py", line 202, in lineReceived
    commands[line]()
  File "/home/david/NuCypher/dev/nucypher/nucypher/utilities/sandbox/ursula.py", line 152, in _paint_known_nodes
    seednode_addresses = list(bn.checksum_address for bn in BOOTNODES)
builtins.NameError: name 'BOOTNODES' is not defined
```

**Comment by tuxxy** [comment]
You need to rebase over @KPrasch's `deployment` branch.

**Comment by KPrasch** [comment]
Yes - I see the Issue. Looks like a bad rename.  I didn't realize this is for the `known_nodes` command at first.
