### ISSUE TITLE
Incompatibility with `py-evm==0.2.0a34`

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#568]
There is a new release of PyEVM: <https://github.com/ethereum/py-evm/releases>.
We currently have `py-evm = ">=0.2.0a33"` in our `Pipfile`.
Installation succeeds, but generated the following output on usage:

```
(nucypher) kieran@pegasus:~/Git/nucypher$ nucypher ursula view
Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.2.2 (/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages), Requirement.parse('eth-utils<2.0.0,>=1.3.0b0'), {'py-evm'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/bin/nucypher", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.2.2 (/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages), Requirement.parse('eth-utils<2.0.0,>=1.3.0b0'), {'py-evm'})

```

**Comment by cygnusv** [comment]
Can we remove dependency on eth-utils 1.2.2? I remember we pinned it because of some problems I found during my installation.

**Comment by KPrasch** [comment]
Yeah - If you have a successful build with newer versions!

At the momet I am able to pin version `0.2.0a33` and the build succeeds, using `pipenv`.

**Comment by mattharrop** [comment]
I am building on an Ubuntu 18.04 box.

After running `pip3 install git+https://github.com/nucypher/nucypher.git@federated`, I have these errors:

```
Successfully built nucypher
py-evm 0.2.0a34 has requirement eth-typing<3.0.0,>=2.0.0, but you'll have eth-typing 1.3.0 which is incompatible.
py-evm 0.2.0a34 has requirement eth-utils<2.0.0,>=1.3.0b0, but you'll have eth-utils 1.2.2 which is incompatible.
```

**Comment by KPrasch** [comment]
We're using versions `> 0.2.0a37` at this point.
