### ISSUE TITLE
No module named 'umbral.fragments'

### ISSUE THREAD

**Issue by Fedma123** [nucypher/nucypher#587]
### Problem
When executing `finnegans-wake-concise-demo.py` on branch `federated`, commit `e822211b4`, the following exception is thrown:
```
Traceback (most recent call last):
  File "finnegans-wake-concise-demo.py", line 8, in <module>
    from nucypher.characters.lawful import Alice, Bob, Ursula
  File "/home/.../nucypher/nucypher/characters/lawful.py", line 39, in <module>
    from nucypher.characters.base import Character, Learner
  File "/home/.../nucypher/nucypher/characters/base.py", line 34, in <module>
    from nucypher.network.middleware import RestMiddleware
  File "/home/.../nucypher/nucypher/network/middleware.py", line 26, in <module>
    from umbral.fragments import CapsuleFrag
ModuleNotFoundError: No module named 'umbral.fragments'
```
By opening a python3 interactive prompt and trying to import `Alice` I get the same exception:
```
>>> from nucypher.characters.lawful import Alice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../nucypher/nucypher/characters/lawful.py", line 39, in <module>
    from nucypher.characters.base import Character, Learner
  File "/home/.../nucypher/nucypher/characters/base.py", line 34, in <module>
    from nucypher.network.middleware import RestMiddleware
  File "/home/.../nucypher/nucypher/network/middleware.py", line 26, in <module>
    from umbral.fragments import CapsuleFrag
ModuleNotFoundError: No module named 'umbral.fragments'
```

### Environment
I followed the installation steps provided in `nucypher/examples/finnegans_wake_demo/README.md`.
Python version is 3.6.7.
At a python3 interactive prompt, I am able to successfully import other nucypher modules.
```
>>> from umbral.keys import UmbralPublicKey
>>> from nucypher.utilities.logging import simpleObserver
```

**Comment by Fedma123** [comment]
Issue seems to be solved in commit 343d50376a320159ccad929904cb60be5c946f7f
