### ISSUE TITLE
Whacky log parsing

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#625]
Trying to log, as a warning, the message from an exception, I expect:

```
Not enough bytes to constitute
                    message types [(None, <class 'umbral.signing.Signature'>, 64, dict)] - need 64, got 0
```

Instead, I get:
```
Not enough bytes to constitute
                    message types [(None, <class 'umbral.signing.Signature'>, 64, dict)] - need 64, got 0
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7fbe30ef0438> due to exception: [Failure instance: Traceback: <class 'KeyError'>: ''
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3267:run_code
<ipython-input-2-3454a5c79a45>:1:<module>
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:238:warn
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py:295:get_field
/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py:252:get_value
]
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7fbe30ef0438> due to exception: [Failure instance: Traceback: <class 'KeyError'>: ''
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3267:run_code
<ipython-input-2-3454a5c79a45>:1:<module>
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:238:warn
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py:295:get_field
/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py:252:get_value
]
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7fbe30ef0438> due to exception: [Failure instance: Traceback: <class 'KeyError'>: ''
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3267:run_code
<ipython-input-2-3454a5c79a45>:1:<module>
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:238:warn
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py:295:get_field
/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py:252:get_value
]
Traceback (most recent call last):
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3454a5c79a45>", line 1, in <module>
    self.log.warn(e.args[0])
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py", line 238, in warn
    self.emit(LogLevel.warn, format, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_flatten.py", line 108, in flattenEvent
    field = aFormatter.get_field(fieldName, (), event)
  File "/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py", line 295, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/home/jmyles/projects/pyenv/versions/3.7.0/lib/python3.7/string.py", line 252, in get_value
    return kwargs[key]
builtins.KeyError: ''
```

**Comment by jMyles** [comment]
Yeah, it's the curlies.  And `replace` after the fact doesn't help in this case, because it's happening in the formatter.
