### ISSUE TITLE
pytest_twisted not working with pytest==4.1.0

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#649]
I ran again a build on master (which was OK yesterday) and now it fails:
https://circleci.com/gh/nucypher/nucypher/9765?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

```
#!/bin/bash -eo pipefail
pipenv run pytest tests/crypto
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.1.0, py-1.7.0, pluggy-0.8.0 -- /home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/bin/python
cachedir: .pytest_cache
rootdir: /home/circleci/nucypher-depends, inifile: pytest.ini
plugins: xdist-1.25.0, twisted-1.8, mypy-0.3.2, mock-1.10.0, forked-0.2, cov-2.5.1
collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/_pytest/main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/_pytest/main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/_pytest/main.py", line 466, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pluggy/manager.py", line 250, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'pytest_twisted' from '/home/circleci/.local/share/virtualenvs/nucypher-depends-V_Q5QYiV/lib/python3.6/site-packages/pytest_twisted.py'>

========================= no tests ran in 0.02 seconds =========================
Exited with code 3
```

I checked the the packages and the only relevant difference in both builds is that `pytest` version is now 4.1.0 (previously, it was 4.0.2). Downgrading to `pytest==4.0.2` fixes the issue.

**Comment by cygnusv** [comment]
Seems addressed in https://github.com/pytest-dev/pytest-twisted/pull/45
Waiting for new release.
