### ISSUE TITLE
Twisted's Logger doesn't like curly braces

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#724]
Once in a while, when revoking, Ursula has trouble logging the event because the string representation of the bytes representation of the revocation ends up having a "{", which the logger doesn't like.

--- <exception caught here> ---
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/home/jmyles/.virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/twisted/logger/_flatten.py", line 87, in flattenEvent
    aFormatter.parse(event["log_format"])
builtins.ValueError: Single '}' encountered in format string
bytes(revocation)
b'REVOKE-\x8fX_Z\xa1\x7f_\x1e\xd9BO]\xcdx\x0c\xfa\x87\x83\x1c\xd8\xd7\xaf\xe9S[\xd3\xd1\x01D[\x0f\x02(\xf51N\x05\xfc]\x95\xf7\xea\xd7x\xb4\xee\xb4<\xad\x9f\xbf&\xf9\x87\x13\x15\xbe\xfa}\x0b\xdb\xab\x8b=\n\x7fG\xfd\x8c\xd6\xdd\xb8\xff\xad\r\x0bj\x0b\xb9\xdf\x80lG.\x87g\xdc\x04\xb9~\x99s\xa9\x8ef\xa4'

**Comment by cygnusv** [comment]
TIL that Twisted's Logger doesn't like curly braces because the[ message string is intended to be compliant to PEP-3101](https://twistedmatrix.com/documents/current/core/howto/logger.html#format-strings), in order to support statements like:
```python
log.info(
    "{request.uri}: status={response.status}, bytes={response.size}, etc...",
    request=request, response=response
)
```
Therefore, if the message string contains characters `{` and `}` intended to be printed, they need [escaping](https://www.python.org/dev/peps/pep-3101/#format-strings). I ran into this issue by trying to debug some stuff, and I've been doing this as a workaround:
```python
message = message.replace("{", "{{").replace("}", "}}")
```

**Comment by cygnusv** [comment]
@KPrasch @jMyles What about monkey-patching `twisted.logger.Logger.emit()`, which is the underlying method that's called anytime we call `debug`, `info`, `warn`, etc. so that the curly braces thing is taken care of there?
The real problem is that we're not using the loggers as they were designed, but at this point, I really prefer to use them our way anyway.

**Comment by jMyles** [comment]
Just seeing this, @cygnusv.  Umm, I don't know if I like a monkeypatch as much as I'd prefer to just write a shim.  What logic are you imagining exactly?  A `replace`?

**Comment by cygnusv** [comment]
I didn't know what a shim was, but after reading about it, I agree it's much better than monkey patching. I don't know how to do it, though, but I'd like to learn what would be the cleanest way to implement it.

**Comment by jMyles** [comment]
Is this sort of thing also part of this?

```
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f6b37f57460> due to exception: [Failure instance: Traceback: <class 'KeyError'>: "'alice_verifying_key'"
/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/controllers.py:316:handle_request
/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/emitters.py:251:exception
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py:206:debug
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_observer.py:131:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_file.py:50:__call__
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py:252:<lambda>
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py:203:eventAsJSON
/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/usr/lib/python3.8/string.py:272:get_field
/usr/lib/python3.8/string.py:229:get_value
]
Traceback (most recent call last):
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/controllers.py", line 316, in handle_request
    return self.emitter.exception(
  File "/home/jmyles/projects/nucypher/nucypher/nucypher/characters/control/emitters.py", line 251, in exception
    logger(message)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py", line 206, in debug
    self.emit(LogLevel.debug, format, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-oH13o4TM/lib/python3.8/site-packages/twisted/logger/_flatten.py", line 108, in flattenEvent
    field = aFormatter.get_field(fieldName, (), event)
  File "/usr/lib/python3.8/string.py", line 272, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 229, in get_value
    return kwargs[key]
builtins.KeyError: "'alice_verifying_key'"
```

**Comment by cygnusv** [comment]
@jMyles I think it's related, although I can't reproduce it for the moment. For the record, some MWE in case someone has the time to try to fix this.

```python
>>> from twisted.logger import Logger
>>> from nucypher.utilities.logging import GlobalLoggerSettings
>>> GlobalLoggerSettings.start_console_logging()
>>> l.info("{asdf}")
Unable to format event {'log_logger': <Logger 'asdf'>, 'log_level': <LogLevel=info>, 'log_namespace': 'asdf', 'log_source': None, 'log_format': '{asdf}', 'log_time': 1595169250.425337}: 'asdf'
>>> l.info(str({'asdf':234}))
Unable to format event {'log_logger': <Logger 'asdf'>, 'log_level': <LogLevel=info>, 'log_namespace': 'asdf', 'log_source': None, 'log_format': "{'asdf': 234}", 'log_time': 1595169448.356728}: "'asdf'"
```

**Comment by cygnusv** [comment]
@jMyles Oh I see what happens, this is for the JSON logging. So, yes, it's the same error:

```python
>>> GlobalLoggerSettings.start_json_file_logging()
>>> l.info(str({'asdf':234}))
Unable to format event {'log_logger': <Logger 'asdf'>, 'log_level': <LogLevel=info>, 'log_namespace': 'asdf', 'log_source': None, 'log_format': "{'asdf': 234}", 'log_time': 1595171002.8230011}: "'asdf'"
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x103e2be80> due to exception: [Failure instance: Traceback: <class 'KeyError'>: "'asdf'"
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py:90:runcode
<input>:1:<module>
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_logger.py:222:info
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:295:get_field
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:252:get_value
]
Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x103e2be80> due to exception: [Failure instance: Traceback: <class 'KeyError'>: "'asdf'"
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py:90:runcode
<input>:1:<module>
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_logger.py:222:info
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_observer.py:131:__call__
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_file.py:50:__call__
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_json.py:252:<lambda>
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_json.py:203:eventAsJSON
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_flatten.py:108:flattenEvent
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:295:get_field
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py:252:get_value
]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
    
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_logger.py", line 222, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_json.py", line 252, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_json.py", line 203, in eventAsJSON
    flattenEvent(event)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/twisted/logger/_flatten.py", line 108, in flattenEvent
    field = aFormatter.get_field(fieldName, (), event)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 295, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 252, in get_value
    return kwargs[key]
builtins.KeyError: "'asdf'"
```
