### ISSUE TITLE
Ensure No Development Dependencies are Required for Standard Installation

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#756]
Demo code needs to run without any of the development dependencies.  W eve had a few recent reports of this happening (see #738 )

**Comment by KPrasch** [comment]
Reproduced Issue report:

```
$ pip3 install nucypher
...
$ nucypher --help
Traceback (most recent call last):
  File "/home/k/Git/nucypher/llamas/bin/nucypher", line 6, in <module>
    from nucypher.cli.main import nucypher_cli
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/cli/main.py", line 27, in <module>
    from nucypher.characters.lawful import Ursula
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 45, in <module>
    from nucypher.blockchain.eth.actors import PolicyAuthor, Miner
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/blockchain/eth/actors.py", line 30, in <module>
    from nucypher.blockchain.eth.agents import NucypherTokenAgent, MinerAgent, PolicyAgent
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 26, in <module>
    from nucypher.blockchain.eth.chains import Blockchain
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/blockchain/eth/chains.py", line 26, in <module>
    from nucypher.blockchain.eth.interfaces import BlockchainInterface, BlockchainDeployerInterface
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/blockchain/eth/interfaces.py", line 39, in <module>
    from nucypher.blockchain.eth.sol.compile import SolidityCompiler
  File "/home/k/Git/nucypher/llamas/lib/python3.6/site-packages/nucypher/blockchain/eth/sol/compile.py", line 25, in <module>
    from solc import install_solc, compile_files
ModuleNotFoundError: No module named 'solc'


```
