### ISSUE TITLE
Certificate Verification Failure Causes Crash

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#765]
v alpha.12

Trying the run the UI heartbeat demo with the EthDenver seednode crashes while learning due to a certificate verification issue:

```
Found 1 known node metadata files at /Users/derek/Documents/Github/repos/forks/derek/nucypher-demos/heartbeat_demo/alicia-files/config_root/known_nodes/metadata
Cycled teachers; New teacher is ⇀Teal King YellowGreen Aries↽ (0x28d9416e5E18821074f376fD333c10AAEB359F7a)
Cycled teachers; New teacher is ⇀Teal King YellowGreen Aries↽ (0x28d9416e5E18821074f376fD333c10AAEB359F7a)
Traceback (most recent call last):
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 357, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='18.188.183.22', port=9151): Max retries exceeded with url: /public_information (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "streaming_heartbeat.py", line 7, in <module>
    import alicia
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-demos/heartbeat_demo/alicia.py", line 76, in <module>
    alicia.start_learning_loop(now=True)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/nucypher/network/nodes.py", line 444, in start_learning_loop
    self.learn_from_teacher_node()
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/nucypher/network/nodes.py", line 769, in learn_from_teacher_node
    certificate_filepath=certificate_filepath)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/nucypher/network/nodes.py", line 964, in verify_node
    certificate_filepath=certificate_filepath)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/nucypher/network/middleware.py", line 203, in node_information
    certificate_filepath=certificate_filepath)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/nucypher/network/middleware.py", line 97, in method_wrapper
    response = self.invoke_method(method, url, verify=certificate_filepath, *args, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/nucypher/network/middleware.py", line 63, in invoke_method
    response = method(url, *args, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/derek/.local/share/virtualenvs/heartbeat_demo-iX64tqBU/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='18.188.183.22', port=9151): Max retries exceeded with url: /public_information (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
(heartbeat_demo)
```

**Comment by KPrasch** [comment]
Solved with `middleware.NodeIsDownMiddleware` testing.
