### ISSUE TITLE
Use a better error when there is no `known_metadata_dir` on destroy attempt

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#784]
```

 ,ggg,         gg                                                     
dP""Y8a        88                                   ,dPYb,            
Yb, `88        88                                   IP'`Yb            
 `"  88        88                                   I8  8I            
     88        88                                   I8  8'            
     88        88   ,gggggg,    ,g,     gg      gg  I8 dP    ,gggg,gg 
     88        88   dP""""8I   ,8'8,    I8      8I  I8dP    dP"  "Y8I 
     88        88  ,8'    8I  ,8'  Yb   I8,    ,8I  I8P    i8'    ,8I 
     Y8b,____,d88,,dP     Y8,,8'_   8) ,d8b,  ,d8b,,d8b,_ ,d8,   ,d8b,
      "Y888888P"Y88P      `Y8P' "YY8P8P8P'"Y88P"`Y88P'"Y88P"Y8888P"`Y8


the Untrusted Re-Encryption Proxy.

Traceback (most recent call last):
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/cli/ursula.py", line 220, in ursula
    log=log)
  File "/home/jmyles/projects/nucypher/nucypher/cli/actions.py", line 31, in destroy_system_configuration
    character_config = config_class.from_configuration_file(filepath=config_file, domains={network})
  File "/home/jmyles/projects/nucypher/nucypher/config/node.py", line 384, in from_configuration_file
    deserializer=cls.NODE_DESERIALIZER)
  File "/home/jmyles/projects/nucypher/nucypher/config/storages.py", line 480, in from_payload
    return cls(*args, **payload, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/config/storages.py", line 296, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'known_metadata_dir'
Sentry is attempting to send 1 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by cygnusv** [comment]
Try `--force`

**Comment by cygnusv** [comment]
Related to #708

**Comment by jMyles** [comment]
Nein.  `--force` has same result.

**Comment by KPrasch** [comment]
See #708
