### ISSUE TITLE
Support multiple character and / or deploy configurations in config directory

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#786]
Presently, if you deploy and then try to init a character, with both in the same default directory (eg `~/.local/share/nucypher`), you get something like this:

```
Traceback (most recent call last):
  File "/home/jmyles/projects/nucypher/nucypher/config/node.py", line 530, in initialize
    os.mkdir(self.config_root, mode=0o755)
FileExistsError: [Errno 17] File exists: '/home/jmyles/.local/share/nucypher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jmyles/.local/share/virtualenvs/nucypher-EzeC4Bqx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jmyles/projects/nucypher/nucypher/cli/ursula.py", line 199, in ursula
    poa=poa)
  File "/home/jmyles/projects/nucypher/nucypher/config/node.py", line 281, in generate
    ursula_config.__write(password=password, no_registry=no_registry)
  File "/home/jmyles/projects/nucypher/nucypher/config/node.py", line 285, in __write
    _new_installation_path = self.initialize(password=password, import_registry=no_registry)
  File "/home/jmyles/projects/nucypher/nucypher/config/node.py", line 535, in initialize
    raise self.ConfigurationError(message)
nucypher.config.node.ConfigurationError: There are existing files located at /home/jmyles/.local/share/nucypher
```

**Comment by KPrasch** [comment]
Fixed in #812
