### ISSUE TITLE
Config Root doesn't work?

### ISSUE THREAD

**Issue by drdgvhbh** [nucypher/nucypher#898]
See the following output. Config file does work though.

```bash
(nucypher) (base) drd@drd-MS-7922:~/Documents/Repositories/nucypher$ nucypher alice run --federated-only --teacher-uri localhost:10151 --config-root ~/.config/cypherdocs/alice


_____   __      _________               ______              
___  | / /___  ___  ____/____  ____________  /______________
__   |/ /_  / / /  /    __  / / /__  __ \_  __ \  _ \_  ___/
_  /|  / / /_/ // /___  _  /_/ /__  /_/ /  / / /  __/  /    
/_/ |_/  \__,_/ \____/  _\__, / _  .___//_/ /_/\___//_/     
                        /____/  /_/                         

version 0.1.0-alpha.21



    / \  | (_) ___ ___
   / _ \ | | |/ __/ _ \
  / ___ \| | | (_|  __/
 /_/   \_|_|_|\___\___|

 the Authority.

Traceback (most recent call last):
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/bin/nucypher", line 10, in <module>
    sys.exit(nucypher_cli())
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/nucypher/cli/characters/alice.py", line 125, in alice
    provider_uri=provider_uri)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/nucypher/config/node.py", line 380, in from_configuration_file
    payload = cls._read_configuration_file(filepath=filepath)
  File "/home/drd/.local/share/virtualenvs/nucypher-msgmh9pD/lib/python3.7/site-packages/nucypher/config/node.py", line 362, in _read_configuration_file
    with open(filepath, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/drd/.local/share/nucypher/alice.config'
Sentry is attempting to send 1 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
(nucypher) (base) drd@drd-MS-7922:~/Documents/Repositories/nucypher$ ls ~/.config/cypherdocs/alice
alice.config  keyring  known_nodes
```

**Comment by KPrasch** [comment]
Hello @drdgvhbh!

The `--config-root` flag is not intended to be used this way. (It is used during `init`).  If you want to use a custom configuration file during the `run` command - you can use the `--config-root` flag.

**Comment by KPrasch** [comment]
Also improved in PR #861
