### ISSUE TITLE
Cannot learn from devnet with domain AttributeError

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#907]
```
2019-04-04T17:31:25-0700 [learning-loop#warn] Unhandled error during node learning: Traceback (most recent call last):
	  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 1272, in run
	    self.mainLoop()
	  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 1281, in mainLoop
	    self.runUntilCurrent()
	  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/kieran/Git/nucypher/nucypher/network/nodes.py", line 534, in keep_learning_about_nodes
	    self.learn_from_teacher_node(eager=False)
	  File "/home/kieran/Git/nucypher/nucypher/network/nodes.py", line 746, in learn_from_teacher_node
	    if not self.learning_domains.intersection(node.serving_domains):
	builtins.AttributeError: 'list' object has no attribute 'intersection'
	

```

**Comment by KPrasch** [comment]
Fixed in #916
