### ISSUE TITLE
TypeError when doing 'nucypher status' upon blockchain connection attempt

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#990]
```Traceback (most recent call last):
  File "/usr/local/bin/nucypher", line 11, in <module>
    load_entry_point('nucypher', 'console_scripts', 'nucypher')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tux/nucypher/nucypher/cli/status.py", line 41, in status
    ursula_config.connect_to_blockchain(provider_uri=ursula_config.provider_uri)
TypeError: connect_to_blockchain() got an unexpected keyword argument 'provider_uri'
```

**Comment by michwill** [comment]
Fixed
